### ISSUE TITLE
Poor/regressive performance using oiiotool to strip channels out of an exr

### ISSUE THREAD

**Issue by mike1158** [OpenImageIO/oiio#1537] opened 2016-10-18 23:12 UTC
This command:

```
oiiotool input.exr --ch R,G,B,A -d half -o output.exr
```

seems to take an inordinate amount of time in 1.6.14 or 1.7.7.  It is faster, but still, I think, underperforming in 1.5.14.  Note the very high system time for 1.6.14 and 1.7.7:

From OpenImageIO-1.5.14:
$ time oiiotool input.exr --ch R,G,B,A -d half -o output.exr
real    0m34.560s
user    0m42.027s
sys     0m0.398s

From OpenImageIO-1.6.14:
$ time oiiotool input.exr --ch R,G,B,A -d half -o output.exr
real    1m56.511s
user    2m45.863s
sys     6m20.403s

From OpenImageIO-1.7.7:
$ time oiiotool input.exr --ch R,G,B,A -d half -o output.exr
real    1m15.012s
user    1m57.619s
sys     6m43.690s

OS is CentOS6.6.  All three versions of OIIO were built against OpenEXR 2.2.0.

Original input.exr file is 20M, output.exr is 279K.  I can supply the input.exr on request.  Output of "oiiotool --info input.exr":

input.exr            : 5760 x 2880, 50 channel, half/half/half/half/float/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half openexr

Sorry, I haven't had time to dig into possible causes yet, but the performance regression seemed bad enough to log an issue.

Cheers,
-miker

**Comment by lgritz** [comment] 2016-10-18 23:55
Whoa, that's crazy! I would have expected a few seconds, not a minute or more. 

I'm working on a theory. Would you mind running it again (with 1.7) using the "--runstats" option and paste the output?

Also, perhaps I can get a peek at the file itself? Is there a version I can download?

**Comment by lgritz** [comment] 2016-10-19 00:06
I tried to reproduce on my end (just using `oiiotool -create 5760x2880 50 -d half -o in.exr`), and then the subsequent `oiiotool in.exr -ch R,G,B,A -o out.exr` runs in about 18 seconds for me, is about the same time regardless of whether I use 1.5/1.6/1.7/master, and in no case does it have a huge 'sys' time. This is all on CentOS 7, and happening over a network disk partition. (Perhaps you can also try that on your end -- does it have similar runtime as your own image?)

Maybe my creating a big black frame is not a good reproduction of the situation, so I'd like to get your file and see if there's anything "special" about it.

Can I assume that `env | grep OPENIMAGEIO` shows that you don't have any environment variables controlling OIIO behavior that isn't apparent from the command line?

**Comment by mike1158** [comment] 2016-10-19 00:08
Hi Larry, thanks for taking a look. :)  Here you go:
      
      $ time oiiotool --runstats input.exr --ch R,G,B,A -d half -o
        output.exr
      
      Threads: 8
      oiiotool runtime statistics:
        Total time: 43.84s
            --ch         : 43.42
            -o           :  0.42
            input        :  0.00
            unaccounted  :  0.00
        Peak memory:    3.7 GB
        Current memory: 3.7 GB
      
      OpenImageIO ImageCache statistics (0x1a07ce0) ver 1.7.7
        Options:  max_memory_MB=4096.0 max_open_files=100
        autotile=4096
                  autoscanline=1 automip=0 forcefloat=1
        accept_untiled=1
                  accept_unmipped=1 read_before_insert=0
        deduplicate=1
                  unassociatedalpha=0 failure_retries=0 
        Images : 1 unique
          ImageInputs : 1 created, 1 current, 1 peak
          Total pixel data size of all images referenced : 3.1
        GB
          Total actual file size of all images referenced :
        19.3 MB
          Pixel data read : 3.1 GB
          File I/O time : 43.3s (5.4s average per thread)
          File open time only : 0.0s
        Tiles: 5 created, 1 current, 4 peak
          total tile requests : 8
          micro-cache misses : 8 (100%)
          main cache misses : 5 (62.5%)
          redundant reads: 0 tiles, 0 B
          Peak cache memory : 3.1 GB
        Image file statistics:
              opens   tiles    MB read   --redundant--   I/O
        time  res              File
            1    1        1     3164.1                     
        43.3s  5760x2880x50.f32  input.exr  UNTILED
      
        Tot:     1        1     3164.1   (    0    0.0)    
        43.3s
        1 not tiled, 1 not MIP-mapped
        Broken or invalid files: 0
      
      real    0m43.880s
      user    1m5.257s
      sys     4m11.703s
      
      Interestingly, adding --runstats seems to cut ~30 seconds off the
      total runtime.  I tried it several times with similar results each
      time.
      
      -miker
      
      
      On 10/18/2016 04:55 PM, Larry Gritz wrote:
    
    
      Whoa, that's crazy! I would have expected a few seconds, not a
        minute or more. 
      I'm working on a theory. Would you mind running it again (with
        1.7) using the "--runstats" option and paste the output?
      Also, perhaps I can get a peek at the file itself? Is there a
        version I can download?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenImageIO/oiio","title":"OpenImageIO/oiio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenImageIO/oiio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lgritz in #1537: Whoa, that's crazy! I would have expected a few seconds, not a minute or more. \r\n\r\nI'm working on a theory. Would you mind running it again (with 1.7) using the \"--runstats\" option and paste the output?\r\n\r\nAlso, perhaps I can get a peek at the file itself? Is there a version I can download?\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/OpenImageIO/oiio/issues/1537#issuecomment-254672720"}}}

**Comment by mike1158** [comment] 2016-10-19 00:09
On 10/18/2016 05:06 PM, Larry Gritz
      wrote:
    
    
      I tried to reproduce on my end (just using oiiotool
          -create 5760x2880 50 -d half -o in.exr), and then the
        subsequent oiiotool in.exr -ch R,G,B,A -o out.exr
        runs in about 18 seconds for me, is about the same time
        regardless of whether I use 1.5/1.6/1.7/master, and in no case
        does it have a huge 'sys' time. This is all on CentOS 7, and
        happening over a network disk partition. (Perhaps you can also
        try that on your end -- does it have similar runtime as your own
        image?)
      Maybe my creating a big black frame is not a good reproduction
        of the situation, so I'd like to get your file and see if
        there's anything "special" about it.
    
    
    I'll get you the source image shortly.  It was a render written out
    of clarisse.
    
    
      Can I assume that env | grep OPENIMAGEIO shows
        that you don't have any environment variables controlling OIIO
        behavior that isn't apparent from the command line?
    
    
    Correct.  No special env vars.
    
    -miker
    
    
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenImageIO/oiio","title":"OpenImageIO/oiio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenImageIO/oiio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lgritz in #1537: I tried to reproduce on my end (just using `oiiotool -create 5760x2880 50 -d half -o in.exr`), and then the subsequent `oiiotool in.exr -ch R,G,B,A -o out.exr` runs in about 18 seconds for me, is about the same time regardless of whether I use 1.5/1.6/1.7/master, and in no case does it have a huge 'sys' time. This is all on CentOS 7, and happening over a network disk partition. (Perhaps you can also try that on your end -- does it have similar runtime as your own image?)\r\n\r\nMaybe my creating a big black frame is not a good reproduction of the situation, so I'd like to get your file and see if there's anything \"special\" about it.\r\n\r\nCan I assume that `env | grep OPENIMAGEIO` shows that you don't have any environment variables controlling OIIO behavior that isn't apparent from the command line?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/OpenImageIO/oiio/issues/1537#issuecomment-254674329"}}}

**Comment by lgritz** [comment] 2016-10-19 00:12
I can categorically say that using --runflags can't possibly affect runtime! All it does is print stats at the end.

Are you sure you weren't experiencing some kind of temporary system or network glitch that was making the file access or computation super slow? Or swapping because of something else running on your system?

**Comment by mike1158** [comment] 2016-10-19 00:16
On 10/18/2016 05:12 PM, Larry Gritz
      wrote:
    
    
      I can categorically say that using --runflags can't possibly
        affect runtime! All it does is print stats at the end.
      Are you sure you weren't experiencing some kind of temporary
        system or network glitch that was making the file access or
        computation super slow? Or swapping because of something else
        running on your system?
    
    
    Well, the input.exr file is in /tmp, and it's running on an
    otherwise idle machine (excepting a couple of shells, firefox, and
    thunderbird).  
    
    Perhaps whatever is causing the high sys time is non-deterministic,
    and I saw a pattern where there wasn't one...
    
    Anyway, I shared the file in question with you on dropbox.  Let me
    know if you didn't get it.
    
    -miker
    
    
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenImageIO/oiio","title":"OpenImageIO/oiio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenImageIO/oiio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lgritz in #1537: I can categorically say that using --runflags can't possibly affect runtime! All it does is print stats at the end.\r\n\r\nAre you sure you weren't experiencing some kind of temporary system or network glitch that was making the file access or computation super slow? Or swapping because of something else running on your system?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/OpenImageIO/oiio/issues/1537#issuecomment-254675144"}}}

**Comment by mike1158** [comment] 2016-10-19 00:23
On 10/18/2016 05:16 PM, Michael Root wrote:
> Perhaps whatever is causing the high sys time is non-deterministic, and I saw 
> a pattern where there wasn't one...

Indeed, that does appear to be the case:

$ time oiiotool --runstats input.exr --ch R,G,B,A -d half -o output.exr > /dev/null
real    1m17.555s
user    2m0.618s
sys     6m53.291s

$ time oiiotool --runstats input.exr --ch R,G,B,A -d half -o output.exr > /dev/null
real    1m17.471s
user    2m0.748s
sys     6m56.312s

$ time oiiotool --runstats input.exr --ch R,G,B,A -d half -o output.exr > /dev/null
real    0m42.364s
user    1m4.081s
sys     4m3.241s

$ time oiiotool --runstats input.exr --ch R,G,B,A -d half -o output.exr > /dev/null
real    1m15.168s
user    1m57.441s
sys     6m39.468s

$ time oiiotool --runstats input.exr --ch R,G,B,A -d half -o output.exr > /dev/null
real    1m17.501s
user    2m0.785s
sys     6m53.984s

$ time oiiotool --runstats input.exr --ch R,G,B,A -d half -o output.exr > /dev/null
real    1m53.006s
user    2m54.149s
sys     8m34.071s

$ time oiiotool --runstats input.exr --ch R,G,B,A -d half -o output.exr > /dev/null
real    1m10.822s
user    1m53.676s
sys     6m24.810s

-miker

**Comment by lgritz** [comment] 2016-10-19 00:24
Whoa! 

Your file takes dramatically longer than mine!

I see now that I misunderstood your original info output -- I thought you had 50 channels, all half, but in fact you have 49 half channels with 1 float channel mixed in. I'm betting that has something to do with it. I'll dig into this some more.

**Comment by lgritz** [comment] 2016-10-19 06:01
Although I'm still trying to understand exactly what's expensive and how to combat it more automatically, I think you might get some relief if you add `--autotile 0` to your oiiotool command line.

**Comment by lgritz** [comment] 2016-10-19 19:58
Question, as I contemplate ways to make this more efficient:

Is your performance-sensitive use of `-ch` always / almost always to isolate RGBA? Always to isolate a small number of "adjacent" channels (in the OIIO sort order that clusters by "layer" name)? Or is the case you're really concerned about requiring truly arbitrary channels gathered sparsely from among the 50+ channels in the source file?

**Comment by mike1158** [comment] 2016-10-19 21:05
Hard to say--I think this is the first time I've used oiiotool for
      this. :)  We had an artist who mistakenly rendered too many
      unneeded AOVs on renders which were being sent directly out the
      door to someone else, so we just wanted to get rid of the extra
      stuff quickly.  I don't think we'd commonly need to pluck out
      arbitrary channels.
      
      Ideally, only the channels actually requested for output or other
      processing would actually be read from the file.  I was recently
      talking to the RV guys about similar issues, as large-format stuff
      is increasingly the norm, and more apps are using extra channels. 
      On a recent show, we saw 6400x6400, 30-channel files at
      ~300MB/frame (48fps, of course) , and I'm sure we'll soon see
      larger.  Being able to slice out RGBA, or RGBAZ from that without
      reading the extra data would be really, really, handy.
      
      -miker
      
      
      On 10/19/2016 12:58 PM, Larry Gritz wrote:
    
    
      Question, as I contemplate ways to make this more efficient:
      Is your performance-sensitive use of -ch always /
        almost always to isolate RGBA? Always to isolate a small number
        of "adjacent" channels (in the OIIO sort order that clusters by
        "layer" name)? Or is the case you're really concerned about
        requiring truly arbitrary channels gathered sparsely from among
        the 50+ channels in the source file?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenImageIO/oiio","title":"OpenImageIO/oiio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenImageIO/oiio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lgritz in #1537: Question, as I contemplate ways to make this more efficient:\r\n\r\nIs your performance-sensitive use of `-ch` always / almost always to isolate RGBA? Always to isolate a small number of \"adjacent\" channels (in the OIIO sort order that clusters by \"layer\" name)? Or is the case you're really concerned about requiring truly arbitrary channels gathered sparsely from among the 50+ channels in the source file?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/OpenImageIO/oiio/issues/1537#issuecomment-254923082"}}}

**Comment by lgritz** [comment] 2016-10-19 21:17
> Being able to slice out RGBA, or RGBAZ from that without reading the extra data would be really, really, handy.

Agreed, I'm just asking how general you think the requirement is, in terms of the "common" case you would like to be extra efficient: (a) first N channels; (b) any N consecutive channels; (c) arbitrary list of potentially non-consecutive channels?

Specifically, I think I can give you (a) or (b) really easily, but (c) is going to be a PITA so I'd rather avoid the work if nobody cares about that case being especially fast. But I'd also prefer not to waste time on a/b if it will go unused because what you really need is (c).

**Comment by mike1158** [comment] 2016-10-19 21:20
Ah.  In that case, I'd say our 80% use case would be (a), 20%
      would be (b), and once in a blue moon, (c).
      
      -miker
      
      On 10/19/2016 02:17 PM, Larry Gritz wrote:
    
    
      
        Being able to slice out RGBA, or RGBAZ from that without
          reading the extra data would be really, really, handy.
      
      Agreed, I'm just asking how general you think the requirement
        is, in terms of the "common" case you would like to be extra
        efficient: (a) first N channels; (b) any N consecutive channels;
        (c) arbitrary list of potentially non-consecutive channels?
      Specifically, I think I can give you (a) or (b) really easily,
        but (c) is going to be a PITA so I'd rather avoid the work if
        nobody cares about that case being especially fast. But I'd also
        prefer not to waste time on a/b if it will go unused because
        what you really need is (c).
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenImageIO/oiio","title":"OpenImageIO/oiio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenImageIO/oiio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lgritz in #1537: \u003e Being able to slice out RGBA, or RGBAZ from that without reading the extra data would be really, really, handy.\r\n\r\nAgreed, I'm just asking how general you think the requirement is, in terms of the \"common\" case you would like to be extra efficient: (a) first N channels; (b) any N consecutive channels; (c) arbitrary list of potentially non-consecutive channels?\r\n\r\nSpecifically, I think I can give you (a) or (b) really easily, but (c) is going to be a PITA so I'd rather avoid the work if nobody cares about that case being especially fast. But I'd also prefer not to waste time on a/b if it will go unused because what you really need is (c).\r\n"}],"action":{"name":"View Issue","url":"https://github.com/OpenImageIO/oiio/issues/1537#issuecomment-254943441"}}}

**Comment by lgritz** [comment] 2016-10-19 21:21
Great. I think there is a straightforward solution to this increasingly common case.

**Comment by lgritz** [comment] 2016-10-19 22:36
BTW, did `--autotile 0` help?

**Comment by mike1158** [comment] 2016-10-19 23:09
No, it didn't help. 
      
      It did, however, help me find another oiiotool bug when I
      ninja-edited the commandline of a running job on the farm that
      happened to be using 1.6.14.  Patch submitted.  :)
      
      -miker
      
      On 10/19/2016 03:36 PM, Larry Gritz wrote:
    
    
      BTW, did --autotile 0 help?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenImageIO/oiio","title":"OpenImageIO/oiio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenImageIO/oiio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lgritz in #1537: BTW, did `--autotile 0` help?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/OpenImageIO/oiio/issues/1537#issuecomment-254961097"}}}

**Comment by lgritz** [comment] 2016-10-20 07:12
OK, I'm pretty sure I've got a solution that speeds this up by 2 orders of magnitude. Code is done, but it's late and I'm too tired to write up the PR. Will do it in the morning. Stay tuned.

**Comment by lgritz** [comment] 2016-10-20 20:38
Here's my proposed solution and results: https://github.com/OpenImageIO/oiio/pull/1541

**Comment by lgritz** [comment] 2016-10-24 23:42
@mike1158 Have you gotten a chance to try this out?

**Comment by mike1158** [comment] 2016-10-25 19:01
Only 60x speedup?  ;)
      
      Seems like a reasonable solution to me.  Thanks for banging this
      out so fast.
      
      I owe you a beer or three!
      
      Cheers,
      -miker
      
      
      
      On 10/20/2016 01:38 PM, Larry Gritz wrote:
    
    
      Here's my proposed solution and results: #1541
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenImageIO/oiio","title":"OpenImageIO/oiio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenImageIO/oiio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lgritz in #1537: Here's my proposed solution and results: https://github.com/OpenImageIO/oiio/pull/1541\r\n"}],"action":{"name":"View Issue","url":"https://github.com/OpenImageIO/oiio/issues/1537#issuecomment-255221233"}}}

**Comment by lgritz** [comment] 2016-10-25 21:20
I don't suppose you can try the patch on your end to make sure it looks good on your files?

**Comment by mike1158** [comment] 2016-10-25 21:56
Hey Larry.  Will try as soon as I get some time.  Hair on fire at
      the moment.  May be a few days :P
      
      -miker
      
      On 10/25/2016 02:20 PM, Larry Gritz wrote:
    
    
      I don't suppose you can try the patch on your end to make sure
        it looks good on your files?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenImageIO/oiio","title":"OpenImageIO/oiio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenImageIO/oiio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lgritz in #1537: I don't suppose you can try the patch on your end to make sure it looks good on your files?\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/OpenImageIO/oiio/issues/1537#issuecomment-256179417"}}}

**Comment by lgritz** [comment] 2016-10-25 21:58
I totally understand! No rush from my end.

I just wanted to make sure there weren't any loose ends before I merge and then promptly purge all the details from my mental cache.

**Comment by lgritz** [comment] 2018-12-28 19:14
I believe this was long ago fixed by #1541. Closing the issue.

**Closed by lgritz** 2018-12-28 19:14 UTC
