### ISSUE TITLE
[BUG] OIIO sample doesn't exit normally with certain DDS files in Windows

### ISSUE THREAD

**Issue by johnfea** [OpenImageIO/oiio#3594] opened 2022-10-10 12:35 UTC
When opening dds_bc* sample images with the following minimal sample the program doesn't exit. Other images do not cause the issue. I only had this issue with Windows build but not in Linux build. It sounds like it could be a threading related issue. It gets stuck after free(pixels); line due to something at read_image().

```
#include <OpenImageIO/imageio.h>
using namespace OIIO;

int main(int argc, char** argv)
{
auto inp = ImageInput::open(argv[1]);
if (! inp)
  return 0;

const ImageSpec &spec = inp->spec();
int xres = spec.width;
int yres = spec.height;
int channels = spec.nchannels;

unsigned char* pixels = (unsigned char*)malloc(xres * yres * channels);
inp->read_image(0,0,0,-1,TypeDesc::UINT8, pixels);
inp->close();
free(pixels);
return 0;
}
```

OIIO master 2022 Oct 06 / 28122968e536feb39541c4
Windows 10 (executable and OIIO cross compiled in Linux Debian 10 with mingw)
x86_64-w64-mingw32-g++-posix (GCC) 10-posix 20210110

**Comment by aras-p** [comment] 2022-10-10 18:42
FWIW I can't reproduce the issue (neither Debug nor Release build type), but I'm using a VS2022-built Windows build of your sample program.

Can you try with a more recent master branch (after Oct 7, i.e. after #3591 was merged)?

**Comment by johnfea** [comment] 2022-10-10 19:19
It still happens with the latest master branch. I guess I will have to take a look at dds_bc code to try to see what causes the issue.

**Comment by lgritz** [comment] 2022-10-10 19:37
The first thing I was going to do was ask @aras-p if he could take a look, but he beat me to it!

Does it do this with any other file types? I'm not sure why dds would be any more of an issue than other files.

Something specific to the mingw cross compile? That's way out of my experience area.

**Comment by johnfea** [comment] 2022-10-11 07:10
I did additional testing and the issue also happens with tif and tx files. Everything else that I tested worked (including png,jpg,bmp,tga,hdr,exr,gif,ico,dpx,rla,pfm).
Of course, it could also be a mingw bug but I've never encountered an issue with it where code compiled but didn't work.
I wonder what dds_bc*, tif and tx files have in common that trigger it.

**Comment by lgritz** [comment] 2022-10-11 07:13
tx **IS** tiff

Maybe both dds and tiff are both using the thread pool internally?

**Comment by aras-p** [comment] 2022-10-11 07:33
Yeah, so far this points to "something something thread pool", since all of those are using OIIO thread pool. But what is the issue, now that's a good question... (I'm trying to figure out how to use this "mingw" thing as we speak, stay tuned...)

**Comment by johnfea** [comment] 2022-10-11 07:52
FYI you probably want either MSYS2 or Mingw-W64-builds from here: https://www.mingw-w64.org/downloads/ . With the latter you might need to manually compile cmake. I haven't used mingw-w64 in Windows in ages, however. Also, all OIIO deps need to be either recompiled or be dynamic libraries because static libraries from VS won't work.

**Comment by johnfea** [comment] 2022-10-11 10:24
I managed to build OIIO with w64devkit in Windows as DLL from the same static dependencies and that didn't have the issue. So its probably a mingw bug and not a bug in OIIO. For me this fixes the problem so this could be closed as "not planned".

**Comment by lgritz** [comment] 2022-10-11 16:03
OK, let's close then. Re-open if you become convinced that there's something we can do on our side to make it better.

We don't "officially" support MinGW (similar to Android, iOS, FreeBSD, etc.), in the sense that none of the main developers use it or are knowledgeable about it, we don't test on it, none of the big studio users need it as far as I know. We just aren't resourced to be comfortable advertising it as being supported. But we know people use it on those platforms, and we've always happily merged PRs from MinGW users to have fixes to make it work. As long as it doesn't break the other platforms, we take the user's word that a PR fixes something on that compiler and incorporate the patch.

That said, if somebody wanted to help set up another Windows CI job in our CI test matrix that was WinGW based, it might help ensure that we aren't casually breaking on MinGW as we add other things and simply don't know if it will work. I wouldn't even know where to start with that project (I can barely keep the Windows CI tests going sometimes, it's just not a platform I work with in my daily life), but would accept a PR from somebody else who sets it up.

**Closed by lgritz** 2022-10-11 16:04 UTC
