### ISSUE TITLE
With, possibly, gcc9 libOpenImageIO_Util link fails

### ISSUE THREAD

**Issue by plater** [OpenImageIO/oiio#2561] opened 2020-04-21 08:14 UTC
I maintain oiio for openSUSE.
Sorry I didn't have the time to search for where this goes wrong but the flag -ldl is missing from the libOpenImageIO link process in v2.0.7. I solve the problem with:
sed -i 's/\-lImath /\-lImath \-ldl /' src/libutil/CMakeFiles/OpenImageIO_Util.dir/link.txt after cmake in the spec file. If this has been fixed in a later version then excuse the noise and I would appreciate a revision number so I can make a patch.

**Comment by hobbes1069** [comment] 2020-04-21 11:25
Dave, I've never run into that issue on Fedora. I wonder if OIIO needs -ldl directly or if it's needed by one of the dependencies and it not getting configured correctly?

Here's my last build of 2.0.7 for Fedora, maybe comparing the logs will be helpful:
https://kojipkgs.fedoraproject.org//vol/fedora_koji_archive05/packages/OpenImageIO/2.0.7/3.fc31/data/logs/x86_64/build.log

**Comment by plater** [comment] 2020-04-21 12:32
Your build doesn't show -ldl for OpenImageIO_Util's link process. The only differences are my gcc is 9.3.1 and python is 3.8. I had to update oiio to > 2 for OpenShadingLanguage 1.11 due to 1.10 failing with LLVM10, also had link time failures due to the new libclang-cpp.
I didn't have the problem with gcc7 I'm going to assume it's gcc-9.3.1 or glibc-devel-2.26?

**Comment by hobbes1069** [comment] 2020-04-21 12:41
It does with the latest build for rawhide though...

```
[ 59%] Linking CXX shared library ../../lib/libOpenImageIO_Util.so
cd /builddir/build/BUILD/oiio-Release-2.1.13.0/build/linux/src/libutil && /usr/bin/cmake -E cmake_link_script CMakeFiles/OpenImageIO_Util.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -g -DNDEBUG -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -shared -Wl,-soname,libOpenImageIO_Util.so.2.1 -o ../../lib/libOpenImageIO_Util.so.2.1.13 CMakeFiles/OpenImageIO_Util.dir/argparse.cpp.o CMakeFiles/OpenImageIO_Util.dir/benchmark.cpp.o CMakeFiles/OpenImageIO_Util.dir/errorhandler.cpp.o CMakeFiles/OpenImageIO_Util.dir/filesystem.cpp.o CMakeFiles/OpenImageIO_Util.dir/farmhash.cpp.o CMakeFiles/OpenImageIO_Util.dir/filter.cpp.o CMakeFiles/OpenImageIO_Util.dir/hashes.cpp.o CMakeFiles/OpenImageIO_Util.dir/paramlist.cpp.o CMakeFiles/OpenImageIO_Util.dir/plugin.cpp.o CMakeFiles/OpenImageIO_Util.dir/SHA1.cpp.o CMakeFiles/OpenImageIO_Util.dir/strutil.cpp.o CMakeFiles/OpenImageIO_Util.dir/sysutil.cpp.o CMakeFiles/OpenImageIO_Util.dir/thread.cpp.o CMakeFiles/OpenImageIO_Util.dir/timer.cpp.o CMakeFiles/OpenImageIO_Util.dir/typedesc.cpp.o CMakeFiles/OpenImageIO_Util.dir/ustring.cpp.o CMakeFiles/OpenImageIO_Util.dir/xxhash.cpp.o  /lib64/libImath.so /lib64/libIex.so /lib64/libHalf.so /lib64/libIlmThread.so -lpthread /usr/lib64/libboost_filesystem.so /usr/lib64/libboost_system.so -lboost_thread -lpthread /usr/lib64/libboost_chrono.so /usr/lib64/libboost_date_time.so /usr/lib64/libboost_atomic.so -lrt -ldl /usr/lib64/libboost_filesystem.so /usr/lib64/libboost_system.so -lboost_thread /usr/lib64/libboost_chrono.so /usr/lib64/libboost_date_time.so /usr/lib64/libboost_atomic.so -lrt -ldl 
cd /builddir/build/BUILD/oiio-Release-2.1.13.0/build/linux/src/libutil && /usr/bin/cmake -E cmake_symlink_library ../../lib/libOpenImageIO_Util.so.2.1.13 ../../lib/libOpenImageIO_Util.so.2.1 ../../lib/libOpenImageIO_Util.so
```
https://kojipkgs.fedoraproject.org//packages/OpenImageIO/2.1.13.0/2.fc33/data/logs/x86_64/build.log

**Comment by plater** [comment] 2020-04-21 12:52
That build has -ldl at the end of the libOpenImageIO_Util link statement:
/usr/lib64/libboost_chrono.so /usr/lib64/libboost_date_time.so /usr/lib64/libboost_atomic.so -lrt -ldl
The question is, where did it come from? I'll have to wait for gcc10 to see if it gets added somehow.

**Comment by plater** [comment] 2020-04-21 13:50
I dropped the sed and patched src/libutil/CMakeLists.txt. It had :
target_link_libraries (OpenImageIO_Util
        PUBLIC
            ${ILMBASE_LIBRARIES}
            ${GCC_ATOMIC_LIBRARIES}
        PRIVATE
            ${SANITIZE_LIBRARIES}
            ${Boost_LIBRARIES}
            ${CMAKE_DL_LIBS}
So I removed ${CMAKE_DL_LIBS} from PRIVATE and placed it under PUBLIC:
target_link_libraries (OpenImageIO_Util
        PUBLIC
            ${ILMBASE_LIBRARIES}
            ${GCC_ATOMIC_LIBRARIES}
            ${CMAKE_DL_LIBS}
        PRIVATE
            ${SANITIZE_LIBRARIES}
            ${Boost_LIBRARIES}
Now -ldl is added to the build. Your rawhide cmake version is the same as mine.

**Comment by mfvescovi** [comment] 2020-10-17 18:47
Hi!

Debian is facing the same issue, as reported in:

  https://bugs.debian.org/934521

**Comment by lgritz** [comment] 2020-10-17 19:01
So we can fix by moving the ${CMAKE_DL_LIBS} from private to public? That's easy enough, I can submit a PR for this. (Only for libOpenImageIO_Util, or also for libOpenImageIO?)

But does anybody understand why? We don't directly expose the dl functions through the OIIO interface. It should meet every definition of private, no?

**Comment by mfvescovi** [comment] 2020-10-17 19:11
Hi again!

I've just realized that, since 2.1.10.1 release, the issue is fixed
(at least in Debian).

Sorry for the noise.

**Comment by lgritz** [comment] 2020-10-17 20:00
Aha, ok, I'll close this, then, since it seems fixed in currently supported releases.

**Closed by lgritz** 2020-10-17 20:00 UTC
