### ISSUE TITLE
[BUG]Read OpenEXR file error in FAT32 driver.

### ISSUE THREAD

**Issue by klydeid** [OpenImageIO/oiio#3781] opened 2023-03-01 03:37 UTC
**Describe the bug**
I have tested another image format like jpg psd png. all is ok except OpenEXR.
i used ImageInput::open() or ImageBuf() function to read these file.

when i change the driver to NTFS. all the image file is ok.

**Platform information:**
 - OIIO branch/version: 2.4.4
 - OS: windows
 - C++ compiler: c++20
 - Any non-default build flags when you build OIIO:

**Comment by lgritz** [comment] 2023-03-01 07:13
You really haven't given us anything to go on. 

Imagine you were assigned to investigate and fix this problem. How far could you get with just what is written above? What else might you need to know to be able to reproduce the symptom?

Some relevant (crucial, actually) information might be:

* The version of OpenEXR you are using, since you are hypothesizing the problem is specific to OpenEXR.
* The actual image file you are unable to read (or are you saying that you can't read ANY exr file whatsoever, and you've tried a bunch?)
* A way to reproduce the problem -- a small program to build and run, or even better would be if you could reproduce the problem with any of the OIIO utilities such as oiiotool, iinfo, or iconvert. If you can read the file and then write it to another file with oiiotool, but it fails with your program, then the chances are very high that the bug is in your program, not in OIIO per se.
* A specific, detailed description of WHAT fails and HOW. What program are you running, with what command line arguments, and what input file? Does it crash? Does it open the file but when you read the data, the values it returns are wrong? Is there any error message, and if so, exactly what does it say?

**Comment by klydeid** [comment] 2023-03-08 09:53
Sorry for my stupid bug report. T T
when i open this exr file with OpenEXR lib. it's working. but when i use ImageInput::open() function it will return a null pointer.
so i used pdb file to debug step by step. 
at last i found that OIIO recognize the EXR file in FAT32 driver "Not a file" by using the Boost-FileSystem module.
so when i compile OIIO with "USE_STD_FILESYSTEM".  i works.
sorry for that:)

**Closed** 2023-03-08 09:53 UTC
