### ISSUE TITLE
Metadata Lost/modified during process

### ISSUE THREAD

**Issue by paulparneix** [OpenImageIO/oiio#2217] opened 2019-04-21 12:18 UTC
### Metadata Lost/modified during process

Hello, I'm using oiio python bindings to open / save images. OpenImageIO reads most of the metadata right, but I have noticed that some metadatas are lost during the writing process.

I have also noticed that some of the metadatas are modified ("Make" and "Camera Model Name") the consequence is that some other softwares (like photogrammetry ones) don't recognize the camera anymore.

**Expected behavior:**  Save all the metadatas, with original "Make" and "Camera Model Name") Ex for Nikon D810 Camera File :  
- Make | NIKON CORPORATION
- Camera Model Name | NIKON D810

**Actual behavior:**  Missing metadatas and modified "Make" and "Camera Model Name" tags ; Ex for Nikon D810 Camera File : 
- Make | Nikon
- Camera Model Name | D810

### Steps to Reproduce
Python code used : 
```Python
import OpenImageIO as oiio
buf = oiio.ImageBuf(in_file)
buf.write(out_file)
```
here are the metadatas that oiio reads from the input image : 
```xml
<ImageSpec version="22">
<x>0</x>
<y>0</y>
<z>0</z>
<width>7380</width>
<height>4928</height>
<depth>1</depth>
<full_x>0</full_x>
<full_y>0</full_y>
<full_z>0</full_z>
<full_width>7380</full_width>
<full_height>4928</full_height>
<full_depth>1</full_depth>
<tile_width>7380</tile_width>
<tile_height>4928</tile_height>
<tile_depth>1</tile_depth>
<format>uint16</format>
<nchannels>3</nchannels>
<channelnames>
<channelname>R</channelname>
<channelname>G</channelname>
<channelname>B</channelname>
</channelnames>
<alpha_channel>-1</alpha_channel>
<z_channel>-1</z_channel>
<deep>0</deep>
<attrib name="ExposureTime" type="float">0.005</attrib>
<attrib name="FNumber" type="float">10</attrib>
<attrib name="Exif:ExposureProgram" type="uint16" description="manual">1</attrib>
<attrib name="Exif:PhotographicSensitivity" type="uint16">100</attrib>
<attrib name="Exif:SensitivityType" type="uint16" description="recommended exposure index">2</attrib>
<attrib name="Exif:DateTimeOriginal" type="string">2019:02:10 20:48:04</attrib>
<attrib name="Exif:DateTimeDigitized" type="string">2019:02:10 20:48:04</attrib>
<attrib name="Exif:ExposureBiasValue" type="rational2i">0/6</attrib>
<attrib name="Exif:MaxApertureValue" type="rational2i">10/10</attrib>
<attrib name="Exif:MeteringMode" type="uint16" description="pattern">5</attrib>
<attrib name="Exif:LightSource" type="uint16" description="flash">4</attrib>
<attrib name="Exif:Flash" type="int" description="no flash, flash supression">16</attrib>
<attrib name="Exif:FocalLength" type="float" description="50 mm">50</attrib>
<attrib name="oiio:MakerNoteOffset" type="int">0</attrib>
<attrib name="Exif:SubsecTime" type="string">59</attrib>
<attrib name="Exif:SubsecTimeOriginal" type="string">59</attrib>
<attrib name="Exif:SubsecTimeDigitized" type="string">59</attrib>
<attrib name="Exif:SensingMethod" type="uint16" description="1-chip color area">2</attrib>
<attrib name="Exif:CustomRendered" type="uint16" description="no">0</attrib>
<attrib name="Exif:ExposureMode" type="uint16" description="manual">1</attrib>
<attrib name="Exif:WhiteBalance" type="uint16" description="manual">1</attrib>
<attrib name="Exif:DigitalZoomRatio" type="rational2i">1/1</attrib>
<attrib name="Exif:FocalLengthIn35mmFilm" type="uint16">50</attrib>
<attrib name="Exif:SceneCaptureType" type="uint16" description="standard">0</attrib>
<attrib name="Exif:GainControl" type="uint16" description="none">0</attrib>
<attrib name="Exif:Contrast" type="uint16" description="normal">0</attrib>
<attrib name="Exif:Saturation" type="uint16" description="normal">0</attrib>
<attrib name="Exif:Sharpness" type="uint16" description="soft">1</attrib>
<attrib name="Exif:SubjectDistanceRange" type="uint16" description="unknown">0</attrib>
<attrib name="oiio:ColorSpace" type="string">sRGB</attrib>
<attrib name="raw:Demosaic" type="string">AHD</attrib>
<attrib name="PixelAspectRatio" type="float">1</attrib>
<attrib name="Make" type="string">Nikon</attrib>
<attrib name="Model" type="string">D810</attrib>
<attrib name="Software" type="string">Ver.1.12 </attrib>
<attrib name="Exif:ISOSpeedRatings" type="int">100</attrib>
<attrib name="Exif:ShutterSpeedValue" type="float" description="1/199 s">7.64386</attrib>
<attrib name="Exif:ApertureValue" type="float" description="f/10.0">6.64386</attrib>
<attrib name="DateTime" type="string">2019-02-10 20:48:04</attrib>
<attrib name="Orientation" type="int" description="normal">1</attrib>
<attrib name="Nikon:EXIF_MaxAp" type="float">1.41421</attrib>
<attrib name="Nikon:FocalLengthIn35mmFormat" type="int">50</attrib>
<attrib name="Nikon:LensID" type="uint64">9823564991931632390</attrib>
<attrib name="Nikon:LensMount" type="int">6</attrib>
<attrib name="Nikon:CameraMount" type="int">6</attrib>
<attrib name="Nikon:LensFeatures_pre" type="string">AF</attrib>
<attrib name="Nikon:LensFeatures_suf" type="string">G </attrib>
<attrib name="Nikon:MinFocal" type="float">50</attrib>
<attrib name="Nikon:MaxFocal" type="float">50</attrib>
<attrib name="Nikon:MaxAp4MinFocal" type="float">1.4</attrib>
<attrib name="Nikon:MaxAp4MaxFocal" type="float">1.4</attrib>
<attrib name="Nikon:CurFocal" type="float">50.3968</attrib>
<attrib name="Nikon:LensFStops" type="int">84</attrib>
<attrib name="Nikon:CanonFocalUnits" type="int">1</attrib>
<attrib name="Nikon:EffectiveMaxAp" type="float">1.41421</attrib>
<attrib name="Nikon:LensIDNumber" type="int">136</attrib>
<attrib name="Nikon:MCUVersion" type="int">75</attrib>
<attrib name="Nikon:LensType" type="int">6</attrib>
<attrib name="Nikon:AFPoint" type="int">0</attrib>
<attrib name="Nikon:ImageStabilization" type="uint8[7]">0, 0, 0, 0, 0, 0, 0</attrib>
<attrib name="Nikon:BodySerial" type="string">8910789</attrib>
<attrib name="Nikon:ActiveDLighting" type="int">0</attrib>
<attrib name="Nikon:ShootingMode" type="int">0</attrib>
<attrib name="Nikon:VRMode" type="int">0</attrib>
<attrib name="Nikon:ContrastDetectAF" type="int">0</attrib>
<attrib name="Nikon:AFAreaMode" type="int">0</attrib>
<attrib name="Nikon:PhaseDetectAF" type="int">0</attrib>
<attrib name="Nikon:FlashExposureCompensation" type="uint8[4]">0, 0, 0, 0</attrib>
<attrib name="Nikon:ExternalFlashExposureComp" type="uint8[4]">0, 0, 0, 0</attrib>
<attrib name="Nikon:FlashExposureBracketValue" type="uint8[4]">0, 0, 0, 0</attrib>
<attrib name="Nikon:FlashMode" type="int">0</attrib>
<attrib name="Nikon:FlashSource" type="int">0</attrib>
<attrib name="Nikon:FlashFirmware" type="uint8[2]">0, 0</attrib>
<attrib name="Nikon:ExternalFlashFlags" type="int">0</attrib>
<attrib name="Nikon:FlashControlCommanderMode" type="int">0</attrib>
<attrib name="Nikon:FlashGroupControlMode" type="uint8[4]">0, 0, 0, 0</attrib>
<attrib name="Nikon:FlashGroupOutputAndCompensation" type="uint8[4]">0, 0, 0, 0</attrib>
<attrib name="Nikon:NEFCompression" type="int">3</attrib>
<attrib name="Nikon:ExposureMode" type="int">0</attrib>
<attrib name="Nikon:ME_WB" type="float[4]">1, 1, 1, 1</attrib>
<attrib name="Nikon:AFFineTune" type="int">0</attrib>
<attrib name="Nikon:AFFineTuneIndex" type="int">255</attrib>
<attrib name="Nikon:AFFineTuneAdj" type="int">0</attrib>
</ImageSpec>
```
As you can see, most of the tags are ok (except Make and Camera Model)

Here is the xml of the output image metadatas using tif format :
```xml
<ImageSpec version="22">
<x>0</x>
<y>0</y>
<z>0</z>
<width>7380</width>
<height>4928</height>
<depth>1</depth>
<full_x>0</full_x>
<full_y>0</full_y>
<full_z>0</full_z>
<full_width>7380</full_width>
<full_height>4928</full_height>
<full_depth>1</full_depth>
<tile_width>7380</tile_width>
<tile_height>4928</tile_height>
<tile_depth>1</tile_depth>
<format>uint16</format>
<nchannels>3</nchannels>
<channelnames>
<channelname>R</channelname>
<channelname>G</channelname>
<channelname>B</channelname>
</channelnames>
<alpha_channel>-1</alpha_channel>
<z_channel>-1</z_channel>
<deep>0</deep>
<attrib name="oiio:BitsPerSample" type="int">16</attrib>
<attrib name="Orientation" type="int" description="normal">1</attrib>
<attrib name="Make" type="string">Nikon</attrib>
<attrib name="Model" type="string">D810</attrib>
<attrib name="Software" type="string">Ver.1.12 </attrib>
<attrib name="DateTime" type="string">2019-02-10 20:48:04</attrib>
<attrib name="tiff:PhotometricInterpretation" type="int">2</attrib>
<attrib name="tiff:PlanarConfiguration" type="int">1</attrib>
<attrib name="planarconfig" type="string">contig</attrib>
<attrib name="tiff:Compression" type="int">8</attrib>
<attrib name="compression" type="string">zip</attrib>
<attrib name="tiff:RowsPerStrip" type="int">32</attrib>
<attrib name="ExposureTime" type="float">0.005</attrib>
<attrib name="FNumber" type="float">10</attrib>
<attrib name="Exif:DateTimeOriginal" type="string">2019:02:10 20:48:04</attrib>
<attrib name="Exif:DateTimeDigitized" type="string">2019:02:10 20:48:04</attrib>
<attrib name="Exif:ShutterSpeedValue" type="float" description="1/199 s">7.64386</attrib>
<attrib name="Exif:ApertureValue" type="float" description="f/10.0">6.64386</attrib>
<attrib name="Exif:Flash" type="int" description="no flash, flash supression">16</attrib>
<attrib name="Exif:FocalLength" type="float" description="50 mm">50</attrib>
<attrib name="Exif:SubsecTime" type="string">59</attrib>
<attrib name="Exif:SubsecTimeOriginal" type="string">59</attrib>
<attrib name="Exif:SubsecTimeDigitized" type="string">59</attrib>
<attrib name="Exif:ColorSpace" type="int">1</attrib>
<attrib name="oiio:ColorSpace" type="string">sRGB</attrib>
</ImageSpec>
```
Here is the output using jpg format, output is different but still missing some tags : 

```xml
<ImageSpec version="22">
<x>0</x>
<y>0</y>
<z>0</z>
<width>7380</width>
<height>4928</height>
<depth>1</depth>
<full_x>0</full_x>
<full_y>0</full_y>
<full_z>0</full_z>
<full_width>7380</full_width>
<full_height>4928</full_height>
<full_depth>1</full_depth>
<tile_width>7380</tile_width>
<tile_height>4928</tile_height>
<tile_depth>1</tile_depth>
<format>uint8</format>
<nchannels>3</nchannels>
<channelnames>
<channelname>R</channelname>
<channelname>G</channelname>
<channelname>B</channelname>
</channelnames>
<alpha_channel>-1</alpha_channel>
<z_channel>-1</z_channel>
<deep>0</deep>
<attrib name="oiio:ColorSpace" type="string">sRGB</attrib>
<attrib name="jpeg:subsampling" type="string">4:2:0</attrib>
<attrib name="Make" type="string">Nikon</attrib>
<attrib name="Model" type="string">D810</attrib>
<attrib name="Software" type="string">Ver.1.12 </attrib>
<attrib name="DateTime" type="string">2019-02-10 20:48:04</attrib>
<attrib name="Orientation" type="uint16" description="normal">1</attrib>
<attrib name="ExposureTime" type="float">0.004999</attrib>
<attrib name="FNumber" type="float">10</attrib>
<attrib name="Exif:ExposureProgram" type="uint16" description="manual">1</attrib>
<attrib name="Exif:PhotographicSensitivity" type="uint16">100</attrib>
<attrib name="Exif:SensitivityType" type="uint16" description="recommended exposure index">2</attrib>
<attrib name="Exif:ExifVersion" type="string">0230</attrib>
<attrib name="Exif:DateTimeOriginal" type="string">2019:02:10 20:48:04</attrib>
<attrib name="Exif:DateTimeDigitized" type="string">2019:02:10 20:48:04</attrib>
<attrib name="Exif:ShutterSpeedValue" type="float" description="1/199 s">7.64386</attrib>
<attrib name="Exif:ApertureValue" type="float" description="f/10.0">6.64386</attrib>
<attrib name="Exif:MeteringMode" type="uint16" description="pattern">5</attrib>
<attrib name="Exif:LightSource" type="uint16" description="flash">4</attrib>
<attrib name="Exif:Flash" type="uint16" description="no flash, flash supression">16</attrib>
<attrib name="Exif:FocalLength" type="float" description="50 mm">50</attrib>
<attrib name="Exif:SubsecTime" type="string">59</attrib>
<attrib name="Exif:SubsecTimeOriginal" type="string">59</attrib>
<attrib name="Exif:SubsecTimeDigitized" type="string">59</attrib>
<attrib name="Exif:FlashPixVersion" type="string">0100</attrib>
<attrib name="Exif:ColorSpace" type="uint16">1</attrib>
<attrib name="Exif:SensingMethod" type="uint16" description="1-chip color area">2</attrib>
<attrib name="Exif:CustomRendered" type="uint16" description="no">0</attrib>
<attrib name="Exif:ExposureMode" type="uint16" description="manual">1</attrib>
<attrib name="Exif:WhiteBalance" type="uint16" description="manual">1</attrib>
<attrib name="Exif:FocalLengthIn35mmFilm" type="uint16">50</attrib>
<attrib name="Exif:SceneCaptureType" type="uint16" description="standard">0</attrib>
<attrib name="Exif:Contrast" type="uint16" description="normal">0</attrib>
<attrib name="Exif:Saturation" type="uint16" description="normal">0</attrib>
<attrib name="Exif:Sharpness" type="uint16" description="soft">1</attrib>
<attrib name="Exif:SubjectDistanceRange" type="uint16" description="unknown">0</attrib>
<attrib name="IPTC:OriginatingProgram" type="string">Ver.1.12 </attrib>
</ImageSpec>
```
You can download the RAW file from Nikon D810 Camera here (~50mo) : 
[mediafire.com/view/g6x5r2jr9lr90gx/DSC_0769.NEF/file](https://www.mediafire.com/view/g6x5r2jr9lr90gx/DSC_0769.NEF/file)

### Versions

* OIIO branch/version: Release/2.0.5
* OS: Windows 10
* C++ compiler:  VC141

**Comment by lgritz** [comment] 2020-12-13 05:37
I regret that we seem to have lost track of this issue, sorry. The link to the RAW file in question is no longer operational, so I can't directly check whether this is still an issue. OIIO has had two major releases (current is 2.2) and also our dependency for reading these files, LibRaw, also has had major releases since this issue was filed, so it's possible that this has been fixed. 

I'm going to close the issue because I don't have the test file to reproduce, but I urge you to check the current OIIO 2.2 release (including building against LibRaw 0.20), and if it's still a problem, please do re-open this issue or file a new one.

Sorry again, entirely my fault for this falling through the cracks.

**Closed by lgritz** 2020-12-13 05:37 UTC
