### ISSUE TITLE
Type Description for half float OpenEXR and full float OpenEXR by reported as oiio.FLOAT 

### ISSUE THREAD

**Issue by simonh10** [OpenImageIO/oiio#1188] opened 2015-07-21 14:52 UTC
Using the python API the image.format() call returns oiio.FLOAT for both 16bit half float EXR files and 32bit float EXR files.
Version:
OpenImageIO 1.4.16
Python 2.7.5

**Comment by lgritz** [comment] 2015-07-21 18:42
Can you be more specific about which API call you're talking about? Which class?

**Comment by simonh10** [comment] 2015-07-22 12:18
The code I'm using is:

image = oiio.ImageBuf(filename)
type_desc = image.spec().format

type_desc seems to be equivalent to oiio.TypeDesc(oiio.FLOAT) for both half and full float EXRs

**Comment by lgritz** [comment] 2015-10-06 06:27
Going through old tickets...

This seems to be fixed in master, and will therefore be in 1.6 when it's branched into a stable release (hopefully in the next several weeks).

Meanwhile, it turns out that in 1.5, the issue is really that half values are promoted to float in the underlying ImageCache that backs an ImageBuf. In the current master, some other deep structural changes made it possible to have ImageCache to store half pixels, so it will report as such.

If you are ok with the internal storage being promoted to float, and merely want to know what the original file was, you can get that by using `nativespec()` rather than `spec()`.

If you also need the actual in-memory storage to be half, you may need to upgrade to master or wait for 1.6.

**Comment by lgritz** [comment] 2016-07-18 05:47
Fixed in 1.6. Closing.

**Closed by lgritz** 2016-07-18 05:47 UTC
