### ISSUE TITLE
Low performances when reading Planar TIF saved from photoshop

### ISSUE THREAD

**Issue by edubois** [OpenImageIO/oiio#1754] opened 2017-08-26 16:27 UTC
I'm having very slow read performances when reading a RGB planar 4K TIF image. When saving the image as interleaved, it's way faster.

### Problem
Might come from libtiff, not sure. Profiling is advised.

### Steps to Reproduce

1. Create 4K noisy RGB image in photoshop
2. Save it as Uncompressed planar RGB image
3. Read it using oiio.

### Versions

* OIIO branch/version: master / all versions
* OS: Windows
* C++ compiler: Visual 2015, C++11 with AVX instructions enabled.

**Comment by lgritz** [comment] 2017-08-26 16:36
Hi, can you provide a little more detail?

Exactly what do you mean by "read it" -- what operation, specifically, and how are you timing it? How much slower is it (with times)? Are you sure that the issue is interleaved/planar versus uncompressed/compressed? Can you share an image (or give us a pure oiiotool command line to generate an image that exhibits the problem)?

**Comment by lgritz** [comment] 2018-04-23 17:52
I think that #1919 is the same issue, and PR #1925 proposes a fix.

**Comment by lgritz** [comment] 2018-11-21 02:51
I think this was fixed long ago by #1925. Closing.

**Closed by lgritz** 2018-11-21 02:51 UTC
