### ISSUE TITLE
maketx SHA1 Hash mismatch

### ISSUE THREAD

**Issue by lvxejay** [OpenImageIO/oiio#2267] opened 2019-06-18 16:49 UTC
### MakeTX generated texture has mismatched SHA1 metadata

The computed `SHA1:` hash of a maketx generated .tx file does not match the `oiio:SHA1` metadata entry of the file. 

**Expected behavior:**   `SHA-1: 3AF103EDE98FD1958BE797C8A8D5DD2BA6CCA8B0`
```
/oiio-2.1.0-dev/bin/oiiotool --hash /local/jwebber/td_test/textures/asphalt_DIFF_sRGB.tx
```
**Output:**
```
./oiio-2.1.0-dev/bin/oiiotool --hash /local/jwebber/td_test/textures/asphalt_DIFF_sRGB.tx
/local/jwebber/td_test/textures/asphalt_DIFF_sRGB.tx : 1024 x 1024, 3 channel, uint16 tiff (+mipmap)
    SHA-1: 3AF103EDE98FD1958BE797C8A8D5DD2BA6CCA8B0
```
**Actual behavior:**   `oiio:SHA-1: E09999D2B8B6C1A8D1F61F4EE25BCD4F75AF3E9E`
```
/oiio-2.1.0-dev/bin/oiiotoo --info -v /local/jwebber/td_test/textures/asphalt_DIFF_sRGB.tx
```
**Output:**
```
oiio:SHA-1: "E09999D2B8B6C1A8D1F61F4EE25BCD4F75AF3E9E"
```
I stumbled upon this while using the Python bindings to compute pixel hashes. Using the `--hash` flag with oiiotool and iinfo outputs the same hash value as `ImageBufAlgo.computePixelHashSHA1()` from the Python bindings:
```py
>>> a = OpenImageIO.ImageBuf("/local/jwebber/td_test/textures/asphalt_DIFF_sRGB.tx")
>>> OpenImageIO.ImageBufAlgo.computePixelHashSHA1(a)
u'3AF103EDE98FD1958BE797C8A8D5DD2BA6CCA8B0'
```
 What is the difference between these two hash strings? Is the hash string `oiio:SHA-1` supposed to match the computed `SHA1:` hash value? If not, is there a way to use the Python API to reliably generate the same oiio:SHA1 hash from the computed hash value?

### Steps to Reproduce
1) Compute the image hash:
`oiiotool --hash file.tx`
2) Print image info and metadata:
`oiiotool --info -v file.tx`

### Samples
Here is a link to the sample .tif and .tx file I generated:
[https://drive.google.com/drive/folders/1fjAwLr45LfqWOEwCWbp-oPwU9US8l4mG?usp=sharing](url)
And this is the full output from `oiiotool --info -v` run on my sample image.
```
./oiio-2.1.0-dev/bin/oiiotool --info -v /local/jwebber/td_test/textures/asphalt_DIFF_sRGB.tx

Reading /local/jwebber/td_test/textures/asphalt_DIFF_sRGB.tx
/local/jwebber/td_test/textures/asphalt_DIFF_sRGB.tx : 1024 x 1024, 3 channel, uint16 tiff
    MIP-map levels: 1024x1024 512x512 256x256 128x128 64x64 32x32 16x16 8x8 4x4 2x2 1x1
    channel list: R, G, B
    tile size: 64 x 64
    compression: "zip"
    DateTime: "2019:06:18 10:29:40"
    fovcot: 1
    Orientation: 1 (normal)
    PixelAspectRatio: 1
    planarconfig: "contig"
    ResolutionUnit: "in"
    Software: "OpenImageIO 2.1.0dev : /opt/oiio-2.1.0-dev/bin/maketx -o /local/jwebber/td_test/textures/asphalt_DIFF_sRGB.tx --oiio --fixnan box3 --constant-color-detect --monochrome-detect --opaque-detect --threads 16 --runstats -v --unpremult --colorconvert sRGB linear /local/jwebber/td_test/textures/asphalt_DIFF_sRGB.tif"
    textureformat: "Plain Texture"
    wrapmodes: "black,black"
    XResolution: 72
    YResolution: 72
    oiio:AverageColor: "0.0360984,0.0310848,0.0291278"
    oiio:BitsPerSample: 16
    oiio:SHA-1: "E09999D2B8B6C1A8D1F61F4EE25BCD4F75AF3E9E"
    tiff:Compression: 8
    tiff:PhotometricInterpretation: 2
    tiff:PlanarConfiguration: 1
```

### Versions

* OIIO branch/version: `Release 2.1.0-dev`
* OS: `Centos 7`
* C++ compiler: `gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)`

**Comment by lgritz** [comment] 2019-06-18 17:55
Not a bug. 

Sorry for the confusingly similar names, but these are not intended to be the same.

The computed SHA1 in the output of "oiiotool -info" is not metadata in the file, it's just informational and primarily for the purpose of unit testing that a file read matches known test reference output without having to compare the full images. It just hashes the pixel values themselves, and it's per subimage/miplevel.

"oiio:SHA-1" is actual metadata in the file (you would see it with "tiffinfo" or "exrheader", for example). It's placed there by maketx and is solely for the use of the TextureSystem to detect duplicate texture files. It is not just a hash of the pixel values, though -- in addition to the pixel values at level 0 of the MIPmap, it also folds in information about some of the command line arguments to maketx (such as the filter name) that affect how the MIP levels were generated.

I probably should have chosen a more unique name for the metadata, like "oiio:texture-fingerprint", to avoid this confusion.

Closing.

**Comment by lvxejay** [comment] 2019-06-18 18:44
Sorry, I'm still a little confused.
`oiiotool --hash` gives me a SHA-1. This value is not metadata, just informational.
`oiiotool --info -v' gives me oiio:SHA-1. This one IS metadata about the file. Is that correct?

**Comment by lgritz** [comment] 2019-06-18 19:12
Pretty close, and I'm sorry if I was imprecise. (I said --info when I meant --hash.)

`oiiotool --info -v` prints all the metadata that is in the file header. (Something like exrheader or tiffinfo would print the same things, more or less.)

`oiiotool --hash` computes "live" (not related to any metadata that was in the file to begin with) a SHA-1 of the pixel values (of each subimage or MIP level separately).

`maketx` computes an unrelated hash that incorporates the level 0 MIPmap pixel values and ALSO a variety of parameters to maketx itself (mostly that control how the subsequent MIP levels should be generated) and stores it in the file metadata as "oiio:SHA-1" (terrible name, sorry). This metadata is consumed by TextureSystem to detect duplicate files without having to read their pixels.

That metadata that maketx puts in its output file would also be reported by anything else that dumps the header info, such as exrheader or tiffinfo.

The hash that `oiiotool --hash` prints, and the "oiio:SHA-1" metadata that maketx/TextureSystem uses, are not attempting to compute the same thing, and are not expected to match.

I admit that these things are confusingly similar. The historical reason for this is that once upon on a time, they were computing the same thing. But we realized that this was a bug in maketx -- it's not enough to hash the pixel values, it needs to know what filters were used, and a few other things, to really and truly know of two textures are identical. So we fixed the hashes that maketx puts in the metadata, but didn't change the name.

**Comment by lgritz** [comment] 2019-06-18 19:12
I'm reopening this issue. I will rename the metadata so that this is no longer confusing.

**Comment by tarjep** [comment] 2019-11-13 18:28
### Generated hash on .EXR doesn't match after conversion to .TX 

So I'm trying to make a tool to convert all textures in a folder (and it's subfolders) to mipmapped tx-files. If the original textures are overwritten I only want to process the changed textures. 
I've already tried using the -u flag with maketx, but it's a bit slow to compute, even if's just checking that all the oiio:SHA-1 hashes are the same and that there's nothing to convert. I need to generate a hash that is comparable between the original texture and the tx texture. There also doesn't seem to be a way to compute the oiio:SHA-1 in "dry run" mode apart from generating a new .tx using the maketx tool (which defeats the whole purpose of my tool).  

I've also looked into the regular --hash flag with oiiotool command to generate a unique hash 
based on the pixel info only. I am aware that this hash is not salted with various maketx options, like the _oiio:SHA-1_ is, but I'm okay with that.
For all the other files I've tested with (.hdr, .jpeg, .png) the hash from the .tx matches the corresponding files, but that's not the case with .exr files.
Is there something I've missed when converting .exr files with maketx or is there a better approach for this? Sorry if some of these questions are a bit stupid, I'm still quite new to programming. :)

**Command:** 
`oiiotool --hash /Users/test/hdri.exr`

**Output:** 
```
/Users/test/hdri.exr : 2048 x 1024, 4 channel, half openexr
    SHA-1: 0B47B433D68C0B7E31BCBD397583BDF05D4007B5
```
**Command:**
`maketx -oiio hdri.exr`
`oiiotool --hash /Users/test/hdri.tx`

**Output:** 
```
/Users/test/hdri.tx  : 2048 x 1024, 4 channel, float tiff (+mipmap)
    SHA-1: AD8F0E5F743819708BD8606F14439DE69D9A8306
```

As you can see the two hashes generated are not the same.

**Command:** 
`oiiotool --info -v /Users/test/hdri.tx`

**Output:** 
```
Reading /Users/test/hdri.tx
/Users/test/hdri.tx  : 2048 x 1024, 4 channel, float tiff
    MIP-map levels: 2048x1024 1024x512 512x256 256x128 128x64 64x32 32x16 16x8 8x4 4x2 2x1 1x1
    channel list: R, G, B, A
    tile size: 64 x 64
    compression: "zip"
    DateTime: "2019:11:13 18:26:39"
    fovcot: 2
    Orientation: 1 (normal)
    planarconfig: "contig"
    Software: "OpenImageIO 2.0.12 : maketx -oiio hdri.exr"
    textureformat: "Plain Texture"
    wrapmodes: "black,black"
    oiio:AverageColor: "5.17147,5.01699,4.9439,1"
    oiio:BitsPerSample: 32
    oiio:SHA-1: "8011AE639448D48821D1626B181F7759477A393F"
    tiff:Compression: 8
    tiff:PhotometricInterpretation: 2
    tiff:PlanarConfiguration: 1
```

**Comment by lgritz** [comment] 2019-11-13 19:59
@tarjep This is the correct behavior.

Your input is a 'half' OpenEXR file. But you are saving using the default TIFF format -- which does not support 'half' pixels -- so it's converting to float values.  The hash is different because the pixels are different.

The reason that the hash stayed the same for your .hdr, .jpeg, and .png is that they all used data types that TIFF supports, so the pixel values in level 0 of the mipmap really are identical to the source image.

A full 32 bit float is not a good choice for a texture, you almost certainly are wasting a lot of disk and memory (texture cache) space for no benefit. If you are using an HDRI map where the source is a 'half' openexr file, I strongly recommend making the texture exr as well:

    maketx hdri.exr -o hdri.tx.exr

**Comment by tarjep** [comment] 2019-11-13 20:45
Ah, I wasn't aware. Thanks for responding so quickly, much appreciated!

Setting the format to exr did it.
`maketx --format exr hdri.exr`

**Comment by lgritz** [comment] 2020-07-12 22:39
Closing, I think the main questions have been answered.

**Closed by lgritz** 2020-07-12 22:39 UTC
