### ISSUE TITLE
read_scanlines on the same channel give different results

### ISSUE THREAD

**Issue by devernay** [OpenImageIO/oiio#1654] opened 2017-03-31 09:36 UTC
### Problem

I'll make it quick, and elaborate later if necessary:

I used to read several times the Y channel from a PNG YA image using read_scanlines(), in order to get the R,G,B channels.

The first channel was right, but the second and third time I read the channel, it looks like it was premultiplied twice.

I fixed this by duplicating the first channel (it was stupid re-reading it anyway), but this may be an OIIO bug too.

Is this normal or should we look deeper inside?

sample PNG YA image:
https://github.com/MrKepzie/Natron/blob/master/Gui/Resources/Images/natronIcon256_linux.png

### Versions

* OIIO branch/version: 1.7
* OS: osx
* C++ compiler: clang

**Comment by lgritz** [comment] 2017-03-31 14:42
Definitely doesn't sound like intended behavior. 

I'll try it out.


On March 31, 2017 2:36:18 AM PDT, "Frédéric Devernay" <notifications@github.com> wrote:
>
>### Problem
>
>I'll make it quick, and elaborate later if necessary:
>
>I used to read several times the Y channel from a PNG YA image using
>read_scanlines(), in order to get the R,G,B channels.
>
>The first channel was right, but the second and third time I read the
>channel, it looks like it was premultiplied twice.
>
>I fixed this by duplicating the first channel (it was stupid re-reading
>it anyway), but this may be an OIIO bug too.
>
>Is this normal or should we look deeper inside?
>
>sample PNG YA image:
>https://github.com/MrKepzie/Natron/blob/master/Gui/Resources/Images/natronIcon256_linux.png
>
>
>### Versions
>
>* OIIO branch/version: 1.7
>* OS: osx
>* C++ compiler: clang
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenImageIO/oiio/issues/1654

-- 
Larry Gritz
lg@larrygritz.com

**Comment by lgritz** [comment] 2017-04-01 15:20
I looked at the code but can't quite spot an obvious problem. Maybe I don't understand how to reproduce it. Can you be a little more specific about the sequence of calls you are making?

You open the file...

Then you read a scanline -- with which variety call, exactly? which channels?
Then you read the same scanline again? With which call?

And the pixel values are different from the second call?

It would be super helpful to have a 10 line snippet of Python (or C++) that reproduces the problem, showing the exact call sequence.

**Comment by lgritz** [comment] 2018-11-05 23:34
This has been sitting around and I never saw a follow-up explain better how to reproduce the problem. Is this still an issue? Or can we close?

**Comment by devernay** [comment] 2018-11-07 19:50
Sorry, I have not time to get back to this. What I was doing previously to read an YA PNG was reading three times the Y channel, on the same scanlines, to get the R, G and B channels. The first time was OK, and the second and third time were not identical to what I got on the first read. I finally fixed it by not re-reading the same scanlines again and again ( https://github.com/NatronGitHub/openfx-io/commit/00fd69f1862c775810f06ca76671093d0bd553e9 ).
You may want to close this bug.

**Comment by lgritz** [comment] 2018-11-07 21:11
OK, closing. Re-file if we're concerned that it's a bug on the OIIO side that we should look into more carefully.

**Closed by lgritz** 2018-11-07 21:11 UTC
