### ISSUE TITLE
bug: oiiotool changes image data when reading/writing exr

### ISSUE THREAD

**Issue by mjmvisser** [OpenImageIO/oiio#770] opened 2013-12-30 21:20 UTC
https://drive.google.com/file/d/0B880qC-5oTaTZVMyMkR0LWdtWlE/edit?usp=sharing

The example here outputs a compressed image, but the bug is also present without the --compression argument. Other images are fine, so I suspect it may have something to do with the mix of 16 and 32 bit channels in this particular image -- oiiotool doesn't preserve the channel depths and outputs an image with all 32-bit channels.

You can run an "oiiotool --diff original.exr compressed.exr", but I also found differences manually by diffing the cameraDepth channel in Nuke.

**Comment by lgritz** [comment] 2018-11-12 07:30
I think this is long since fixed. I can't reproduce it on a modern version. Closing.

**Closed by lgritz** 2018-11-12 07:30 UTC
