### ISSUE TITLE
[BUG] converting to half with oiiotool actually converts to float

### ISSUE THREAD

**Issue by abrock** [OpenImageIO/oiio#3867] opened 2023-06-07 11:30 UTC
**Describe the bug**

The only related bug I found is #85 which says support for 16bit floating point is done.

I have 16bit integer tiff images (greyscale) I want to convert to 16bit floating point tiff images.
I tried this:
`oiiotool 16bit-integer.tiff -d half -o test-half.tif`

It doesn't print any error or warning messages but it produces a 32bit float image:
`test-half.tif        : 3000 x 4096, 1 channel, float tiff`
And the image has twice the size (in MB) than the original.

I was wondering if it's at all possible to create a 16bit float tiff opened the image in GIMP, set the precision to `16bit floating point` and saved the result:
`test-half-gimp.tif   : 3000 x 4096, 1 channel, half tiff`
And the image has the same size as the original, so it seems possible in principle.

**To Reproduce**

1. Convert a 16bit image to a 16bit floating point using oiiotool.
2. Check the type of the resulting image and find that it actually contains 32bit floating point data

**Expected behavior**

Get a 16bit floating point image

**Platform information:**
 - OIIO branch/version: OpenImageIO 2.2.10
 - OS: Debian bullseye
 - C++ compiler: Unknown, was built by Debian maintainers

**Comment by enziop** [comment] 2023-06-07 12:07
I can confirm the issue for version 2.4.10.0 on archlinux
It only happens for tiff output, works fine for exr

**Comment by lgritz** [comment] 2023-06-07 22:07
In general, because fp16-in-TIFF is pretty sketchy and the vast majority of non-OIIO software will fail to understand it correctly, I recommend using OpenEXR files any time you intend to specifically store fp16 data. But like I said, the one exception to the rule is if you know that it's OIIO-based software on the reading end as well (or something else that you have verified can understand those files correctly).

**Comment by abrock** [comment] 2023-06-08 12:59
Thank you for the detailed explanation. I think I'll use OpenEXR.

I think oiiotool could print a warning when it decides not to use the type requested by the user and it should print a warning in verbose mode, at the moment it doesn't:

```
./oiiotool 32f.tiff -d half -v -o test.tif
Writing test.tif
```

**Comment by lgritz** [comment] 2023-06-08 20:19
I was thinking the same thing as I was writing that up -- a warning might be helpful.

Unfortunately, it's not quite as easy as you think. There is a technical hurdle and a policy hurdle: 

On the technical front, ImageOutput has an error()/geterror() methods, but currently no way to report or retrieve warnings. We can't just dump warnings to the console output from inside the ImageOutput implementation because (a) that's a jerk move for a library to do, and (b) on Windows especially, the library may be used from a GUI app where there is no console output.

On the policy side, the whole idea behind OIIO is to make the app not have to care about what the exact file format being used is. You're just supposed to say "open, output this, done" without needing to know any of the details of the file format and its limitations, and the implementation is supposed to -- if at all possible -- just do the closest sensible thing to what the user asked for, within the constraints of that particular file format. There can be errors, but that only happens when it just can't find a reasonable way to proceed. It's not designed for all sorts of things to generate warnings where the client code would need to check each call and understand what the warning means and take format-specific actions.

But still, warnings make sense, especially from the point of view of oiiotool. I'm just not quite sure what is the right way to wire it all up quite yet. But I will think about it and propose something.

**Comment by lgritz** [comment] 2023-06-08 20:19
Closing this issue for now, since it's not a bug.

**Closed by lgritz** 2023-06-08 20:19 UTC
