### ISSUE TITLE
Impossible to use OIIO libraries built from source

### ISSUE THREAD

**Issue by Iktomist** [OpenImageIO/oiio#3972] opened 2023-09-01 20:47 UTC
I don't have a single bug report to file, because I've been struggling with compiling OpenImageIO as a library, from source, for about four weeks.

No matter what I do, even if the build succeeds, no matter what version of OpenImageIO or what version of Blender, it always leads to some kind of failure somewhere down the line.

With a fresh pull of OIIO 2.5.2, Blender compiles as expected, but make fails in the linking stage due to numerous (thousands and thousands) of undefined references in OIIO. 

This is with both Clang lld and GNU ld.

Here is my error message:

[100%] Linking CXX executable ../../bin/blender
ld: error: undefined symbol: OpenImageIO_v2_5_2::c_str(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>)
>>> referenced by string.cpp
>>>               string.cpp.o:(ccl::string_startswith(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>)) in archive ../../lib/libcycles_util.a
>>> referenced by string.cpp
>>>               string.cpp.o:(ccl::string_endswith(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>)) in archive ../../lib/libcycles_util.a

ld: error: undefined symbol: OpenImageIO_v2_5_2::Sysutil::this_program_path[abi:cxx11]()
>>> referenced by path.cpp
>>>               path.cpp.o:(ccl::path_get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_util.a
>>> referenced by path.cpp
>>>               path.cpp.o:(ccl::path_user_get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_util.a

ld: error: undefined symbol: OpenImageIO_v2_5_2::Filesystem::last_write_time(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, long)
>>> referenced by path.cpp
>>>               path.cpp.o:(ccl::path_cache_kernel_exists_and_mark_used(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_util.a
>>> referenced by path.cpp
>>>               path.cpp.o:(ccl::path_cache_kernel_mark_added_and_clear_old(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned long)) in archive ../../lib/libcycles_util.a

ld: error: undefined symbol: OpenImageIO_v2_5_2::Filesystem::last_write_time(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>)
>>> referenced by path.cpp
>>>               path.cpp.o:(ccl::path_cache_kernel_mark_added_and_clear_old(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned long)) in archive ../../lib/libcycles_util.a

ld: error: undefined symbol: OpenImageIO_v2_5_2::ustring::make_unique(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>)
>>> referenced by denoise.cpp
>>>               denoise.cpp.o:(ccl::NodeType const* ccl::DenoiseParams::register_type<ccl::DenoiseParams>()) in archive ../../lib/libcycles_device.a
>>> referenced by denoise.cpp
>>>               denoise.cpp.o:(ccl::NodeType const* ccl::DenoiseParams::register_type<ccl::DenoiseParams>()) in archive ../../lib/libcycles_device.a
>>> referenced by denoise.cpp
>>>               denoise.cpp.o:(ccl::NodeType const* ccl::DenoiseParams::register_type<ccl::DenoiseParams>()) in archive ../../lib/libcycles_device.a
>>> referenced 2623 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageSpec::ImageSpec(OpenImageIO_v2_5_2::TypeDesc)
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::TileManager()) in archive ../../lib/libcycles_session.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::update(ccl::BufferParams const&, ccl::Scene const*)) in archive ../../lib/libcycles_session.a
>>> referenced by merge.cpp
>>>               merge.cpp.o:(ccl::ImageMerger::run()) in archive ../../lib/libcycles_session.a
>>> referenced 23 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ustring::empty_std_string[abi:cxx11]
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::update(ccl::BufferParams const&, ccl::Scene const*)) in archive ../../lib/libcycles_session.a
>>> referenced by path_trace.cpp
>>>               path_trace.cpp.o:(ccl::PathTrace::process_full_buffer_from_disk(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>)) in archive ../../lib/libcycles_integrator.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::node_socket_attribute_name(ccl::SocketType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_session.a
>>> referenced 36 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ParamValue::clear_value()
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::update(ccl::BufferParams const&, ccl::Scene const*)) in archive ../../lib/libcycles_session.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::update(ccl::BufferParams const&, ccl::Scene const*)) in archive ../../lib/libcycles_session.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::update(ccl::BufferParams const&, ccl::Scene const*)) in archive ../../lib/libcycles_session.a
>>> referenced 51 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageSpec::ImageSpec(int, int, int, OpenImageIO_v2_5_2::TypeDesc)
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::update(ccl::BufferParams const&, ccl::Scene const*)) in archive ../../lib/libcycles_session.a
>>> referenced by openimageio_support.cc
>>>               openimageio_support.cc.o:(blender::imbuf::imb_create_write_context(char const*, ImBuf*, int, bool)) in archive ../../lib/libbf_imbuf_openimageio.a
>>> referenced by openimageio_support.cc
>>>               openimageio_support.cc.o:(blender::imbuf::imb_create_write_context(char const*, ImBuf*, int, bool)) in archive ../../lib/libbf_imbuf_openimageio.a
>>> referenced 1 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageSpec::attribute(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, OpenImageIO_v2_5_2::TypeDesc, void const*)
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::update(ccl::BufferParams const&, ccl::Scene const*)) in archive ../../lib/libcycles_session.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::node_to_image_spec_atttributes(OpenImageIO_v2_5_2::ImageSpec*, ccl::Node const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_session.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::node_to_image_spec_atttributes(OpenImageIO_v2_5_2::ImageSpec*, ccl::Node const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_session.a
>>> referenced 23 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageSpec::attribute(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, OpenImageIO_v2_5_2::ustring)
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::node_to_image_spec_atttributes(OpenImageIO_v2_5_2::ImageSpec*, ccl::Node const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_session.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::node_to_image_spec_atttributes(OpenImageIO_v2_5_2::ImageSpec*, ccl::Node const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_session.a

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageOutput::create(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, OpenImageIO_v2_5_2::Filesystem::IOProxy*, OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>)
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::open_tile_output()) in archive ../../lib/libcycles_session.a
>>> referenced by merge.cpp
>>>               merge.cpp.o:(ccl::ImageMerger::run()) in archive ../../lib/libcycles_session.a
>>> referenced by denoising.cpp
>>>               denoising.cpp.o:(ccl::DenoiseImage::save_output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&)) in archive ../../lib/libcycles_session.a
>>> referenced 1 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageOutput::geterror[abi:cxx11](bool) const
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::open_tile_output()) in archive ../../lib/libcycles_session.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::write_tile(ccl::RenderBuffers const&)) in archive ../../lib/libcycles_session.a
>>> referenced by merge.cpp
>>>               merge.cpp.o:(ccl::ImageMerger::run()) in archive ../../lib/libcycles_session.a
>>> referenced 5 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageInput::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, OpenImageIO_v2_5_2::ImageSpec const*, OpenImageIO_v2_5_2::Filesystem::IOProxy*)
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::read_full_buffer_from_disk(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, ccl::RenderBuffers*, ccl::DenoiseParams*)) in archive ../../lib/libcycles_session.a
>>> referenced by merge.cpp
>>>               merge.cpp.o:(ccl::ImageMerger::run()) in archive ../../lib/libcycles_session.a
>>> referenced by denoising.cpp
>>>               denoising.cpp.o:(ccl::DenoiseImage::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&)) in archive ../../lib/libcycles_session.a
>>> referenced 1 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageSpec::get_int_attribute(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, int) const
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::read_full_buffer_from_disk(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, ccl::RenderBuffers*, ccl::DenoiseParams*)) in archive ../../lib/libcycles_session.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::node_from_image_spec_atttributes(ccl::Node*, OpenImageIO_v2_5_2::ImageSpec const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_session.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::node_from_image_spec_atttributes(ccl::Node*, OpenImageIO_v2_5_2::ImageSpec const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_session.a
>>> referenced 2 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageInput::geterror[abi:cxx11](bool) const
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::read_full_buffer_from_disk(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, ccl::RenderBuffers*, ccl::DenoiseParams*)) in archive ../../lib/libcycles_session.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::TileManager::read_full_buffer_from_disk(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, ccl::RenderBuffers*, ccl::DenoiseParams*)) in archive ../../lib/libcycles_session.a
>>> referenced by openimageio_support.cc
>>>               openimageio_support.cc.o:(blender::imbuf::imb_oiio_read(blender::imbuf::ReadContext const&, OpenImageIO_v2_5_2::ImageSpec const&, char*, OpenImageIO_v2_5_2::ImageSpec&)) in archive ../../lib/libbf_imbuf_openimageio.a
>>> referenced 1 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageSpec::get_float_attribute(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, float) const
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::node_from_image_spec_atttributes(ccl::Node*, OpenImageIO_v2_5_2::ImageSpec const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_session.a
>>> referenced by openimageio_support.cc
>>>               openimageio_support.cc.o:(blender::imbuf::imb_oiio_read(blender::imbuf::ReadContext const&, OpenImageIO_v2_5_2::ImageSpec const&, char*, OpenImageIO_v2_5_2::ImageSpec&)) in archive ../../lib/libbf_imbuf_openimageio.a
>>> referenced by openimageio_support.cc
>>>               openimageio_support.cc.o:(blender::imbuf::imb_oiio_read(blender::imbuf::ReadContext const&, OpenImageIO_v2_5_2::ImageSpec const&, char*, OpenImageIO_v2_5_2::ImageSpec&)) in archive ../../lib/libbf_imbuf_openimageio.a

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageSpec::get_string_attribute(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>) const
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::node_from_image_spec_atttributes(ccl::Node*, OpenImageIO_v2_5_2::ImageSpec const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_session.a
>>> referenced by tile.cpp
>>>               tile.cpp.o:(ccl::node_from_image_spec_atttributes(ccl::Node*, OpenImageIO_v2_5_2::ImageSpec const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)) in archive ../../lib/libcycles_session.a
>>> referenced by merge.cpp
>>>               merge.cpp.o:(ccl::ImageMerger::run()) in archive ../../lib/libcycles_session.a
>>> referenced 6 more times

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageSpec::find_attribute(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, OpenImageIO_v2_5_2::TypeDesc, bool) const
>>> referenced by merge.cpp
>>>               merge.cpp.o:(ccl::ImageMerger::run()) in archive ../../lib/libcycles_session.a
>>> referenced by denoising.cpp
>>>               denoising.cpp.o:(ccl::DenoiseImage::parse_channels(OpenImageIO_v2_5_2::ImageSpec const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&)) in archive ../../lib/libcycles_session.a

ld: error: undefined symbol: OpenImageIO_v2_5_2::ImageSpec::attribute(OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>, OpenImageIO_v2_5_2::TypeDesc, OpenImageIO_v2_5_2::basic_string_view<char, std::char_traits<char>>)
>>> referenced by merge.cpp
>>>               merge.cpp.o:(ccl::ImageMerger::run()) in archive ../../lib/libcycles_session.a
>>> referenced by merge.cpp
>>>               merge.cpp.o:(ccl::ImageMerger::run()) in archive ../../lib/libcycles_session.a
>>> referenced by merge.cpp
>>>               merge.cpp.o:(ccl::merge_layer_render_time(OpenImageIO_v2_5_2::ImageSpec&, ccl::vector<ccl::MergeImage, ccl::GuardedAllocator<ccl::MergeImage>> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, bool)) in archive ../../lib/libcycles_session.a
>>> referenced 1 more times

ld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [source/creator/CMakeFiles/blender.dir/build.make:425: bin/blender] Error 1
make[1]: *** [CMakeFiles/Makefile2:8018: source/creator/CMakeFiles/blender.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

 - OIIO branch/version: 2.5.2 built from source
 - OS: Ubuntu 2304
 - C++ compiler: Clang++ with lld and GNU g++ with GNU ld
 - Any non-default build flags when you build OIIO: I actually compiled it with stop on warning.

**Comment by lgritz** [comment] 2023-09-01 21:14
@jessey-git Any insight here?

The highest supported version of OIIO is 2.4.15.0 (released just today), so if you're using "2.5", it means you're pulling from somewhere in the master development branch. I'm not sure what the implications are of that to the Blender build.to build a

It's hard to tell what's going on here without seeing your full OIIO (and blender?) build logs, but if I had to take a guess, I'd say that it's acting a lot like your build of Blender was seeing headers from one OIIO version, but trying to link against a different version. Is it possible you have multiple OIIO versions installed?

**Comment by jessey-git** [comment] 2023-09-01 21:48
Not too much insight from what was given.  Typically folks will use our pre-compiled libraries for all of the dependencies (precisely because everything is so hard to build with c++).  That said, Blender is currently on 2.4.11+some patches and we haven't attempted 2.5 yet.  I wouldn't expect utter catastrophe moving to 2.5 but it would mean recompiling some of the other dependencies like OSL too at the same time etc.

Generally though, errors like this are caused by slight differences between the build parameters. @Iktomist you can try the following:
- Start with a completely clean Blender build directory. Just wipe it.
- Look at our cmake file for OpenImageIO. This is the one our platform maintainers use to build the dependency and pay close attention to each option enabled; ie. things like `set(OPENIMAGEIO_LINKSTATIC -DLINKSTATIC=OFF)` and `-DBUILD_SHARED_LIBS=ON`
https://projects.blender.org/blender/blender/src/branch/main/build_files/build_environment/cmake/openimageio.cmake

Since this is specific to integration with Blender, if you still have trouble please post at https://devtalk.blender.org/c/building-blender/11 as our platform maintainers have a better chance of seeing it there and providing more tailored help.

**Comment by lgritz** [comment] 2023-09-01 22:07
For a clean build, I don't expect trouble moving from 2.4 to 2.5 per se. But if you mix components built against 2.4 with things built against 2.5, or if you have both installed and end up with a mismatch of headers vs libraries, this kind of "missing symbol" link error is exactly what I'd expect.

**Comment by Iktomist** [comment] 2023-09-02 01:57
Wow, I did not know that the development branch was untested/unsupported for Blender! I will attempt all of these fixes and report back. Thank you very much, everyone.

**Comment by lgritz** [comment] 2023-09-02 03:26
Like I said, I don't necessarily know that there's any problem with 2.5 and Blender. But definitely there will be problems if 2.4 and 2.5 get mixed up in the same build. That's more what I was suspecting.

Within the next day or two, I'll tag the beta for 2.5. So hopefully somebody on the Blender side will ensure that it works in your build before it becomes the new supported version in a few weeks.

**Comment by lgritz** [comment] 2023-09-27 18:56
I think this is ready to close. Please re-open if you think there is something actionable that hasn't yet been resolved.

**Closed by lgritz** 2023-09-27 18:56 UTC
