### ISSUE TITLE
Error in exroutput with subimages

### ISSUE THREAD

**Issue by edgarv** [OpenImageIO/oiio#656] opened 2013-08-14 21:33 UTC
There is a problem in exroutput (using OpenEXR 2) when writing subimages: the member variable `OpenEXROutput::m_pixeltype` is [overwritten](/OpenImageIO/oiio/blob/d585c2d/src/openexr.imageio/exroutput.cpp#L462) when opening an output file using `OpenEXROutput::open (const std::string &, int, const ImageSpec *)`.

This issue generates in an [out-of-bounds exception](/OpenImageIO/oiio/blob/d585c2d/src/openexr.imageio/exroutput.cpp#L999-1002) when running the OpenEXR-v2 test suite with debugging enabled:

```shell
$ oiiotool --stats ../../../../../openexr-images/v2/Stereo/composited.exr -o composited.exr
```
That file contains 4 subimages with 4,1,4,1 channels respectively. After returning from `OpenEXROutput::open`, `m_pixeltype` will have been overwritten 4 times so its final size is one. Thus when oiiotool tries to write the first subimage, which contains 4 channels, there is an error. This problem is not apparent in release mode as all the channels in each subimage are of the same type (half) and the contents of `m_pixeltype` are not actually cleared after being overwritten.

**Comment by lgritz** [comment] 2015-10-06 06:55
This sort of rings a bell as something we fixed, though apparently didn't return and close this issue. But I can't find the specific closed PR that implemented it.

Is this still an issue for you? I'm unable to reproduce the symptoms in the current master.

**Comment by edgarv** [comment] 2015-10-06 08:00
I think fd23ba4 fixed it. (I can only find the commit, not a PR for it.) I remember running the tests on debug mode not long ago and the problem was gone.

**Comment by lgritz** [comment] 2015-10-06 14:34
Thanks.

**Closed by lgritz** 2015-10-06 14:34 UTC
Labels: formats
