### ISSUE TITLE
[BUG] webp plugin corrupts ImageBuf

### ISSUE THREAD

**Issue by MickeyKnox** [OpenImageIO/oiio#2725] opened 2020-09-26 19:55 UTC
In my first attempt to integrate OpenImageIO in my app I created a local variable for ImageBuf in a function. Later I made the ImageBuf a class variable, reusing it for various images with ImageBuf::reset. But then I noticed something peculiar: Some webp images won't load anymore. There is an error in the ImageBuf::get_pixels function that does not appear, when I have one ImageBuf instance per image. I tried to assign a new ImageBuf per image to the variable with the copy constructor without luck. But when I made the variable a pointer and created a new ImageBuf for every image with 'new' the issue is solved.

The issue does not appear with jpg images, only with webp images. I think some internal variables are not properly cleaned by ImageBuf::reset and when a new webp image is bigger than the one before the error triggers.

**Comment by lgritz** [comment] 2020-09-26 21:10
Weird! I don't have a good hypothesis for how this would happen. 

Does this happen reliably with particular webp images (but not others)? Can you send me one that exhibits the problem?

Can it be reproduced from Python, and if so, is there a short repro python example?

**Comment by MickeyKnox** [comment] 2020-09-27 00:15
Ok, I've made some progress. I've filed another issue before about animated webp images being unsupported:

[Animated webp images unsupported #2721](https://github.com/OpenImageIO/oiio/issues/2721)

So far it looks like this to me: Once it was attempted to open an animated webp image (and failing), further attempts to open another (not animated) webp image will fail with the same ImageBuf object. However, jpg images can be opened with the same ImageBuf object afterwards. And whats even more interesting, once a jpg image has been opened succesfully, webp images can also be opened again with the same ImageBuf object.

Thus, it looks like that ImageBuf gets corrupted by animated webp images, but only for other webp images.

**Comment by lgritz** [comment] 2020-10-05 00:26
While I don't have a hypothesis for what might be going wrong here, since you seem to think it's specific to webp, let's try applying the fix proposed in #2730 (fixes #2721), and see if it also makes the symptoms of this issue disappear. If it still persists, and is not fixed by 2730, I will try to reproduce and track it down.

**Comment by lgritz** [comment] 2020-10-22 00:22
@MickeyKnox Is this one also fixed by #2730, or is there also something to look at here?

**Comment by MickeyKnox** [comment] 2020-10-22 16:40
Looks like this is fixed as well, thanks.

**Comment by lgritz** [comment] 2020-10-22 16:52
Closing, solved by #2730

**Closed by lgritz** 2020-10-22 16:52 UTC
