### ISSUE TITLE
I can't display EXR files whith subimage  generated with OIIOTool  "--siappendall" command [HELP]

### ISSUE THREAD

**Issue by jmmsalvador** [OpenImageIO/oiio#2570] opened 2020-04-27 14:43 UTC
**PLEASE DO NOT ASK USAGE QUESTIONS USING GITHUB "ISSUES"**

If you are pretty sure that you have identified a **BUG** in OpenImageIO,
please file a [bug report issue](https://github.com/OpenImageIO/oiio/issues/new?template=bug_report.md).

But if you are just asking a question:
* How do I...?
* I need help with...
* Am I doing something wrong?
* I can't build OpenImageIO

For anything of this nature, the best way to get help using OpenImageIO is
to ask a question on the [oiio-dev developer mail list](http://lists.openimageio.org/listinfo.cgi/oiio-dev-openimageio.org).

The [documentation](https://openimageio.readthedocs.org)
is pretty comprehensive, so please check there first; you may find the answer
more quickly than you can get your question answered on the mail list.

**Comment by lgritz** [comment] 2020-04-27 19:37
As stated above... this is really the kind of question best asked on the mail list rather than filing an issue.

Can you be more specific? Like, tell us EXACTLY the oiiotool command line you used to make an image (including which version of oiio), and EXACTLY what you mean by "can't display"? Using what display program?

**Comment by jmmsalvador** [comment] 2020-04-28 14:35
Which version of oiio
OpenImageIO-Arnold 2.1.4dev

Nuke version
11.3v3

The oiiotool command line I used

oiiotool 
\aov\beauty\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "beauty" 
\aov\N\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "N" 
\aov\Nf\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "Nf" 
\aov\P\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "P" 
\aov\Pf\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "Pf" 
\aov\Pref\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "Pref"  
\aov\Zf\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "Zf" 
\aov\coat_direct\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "coat_direct" 
\aov\coat_indirect\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "coat_indirect" 
\aov\crypto_asset\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "crypto_asset" 
\aov\crypto_material\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "crypto_material" 
\aov\crypto_object\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "crypto_object" 
\aov\diffuse_direct\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "diffuse_direct" 
\aov\diffuse_indirect\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "diffuse_indirect" 
\aov\emission\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "emission" 
\aov\sheen_direct\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "sheen_direct" 
\aov\sheen_indirect\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "sheen_indirect" 
\aov\specular_direct\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "specular_direct" 
\aov\specular_indirect\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "specular_indirect" 
\aov\sss_direct\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "sss_direct" 
\aov\sss_indirect\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "sss_indirect" 
\aov\transmission_direct\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "transmission_direct" 
\aov\transmission_indirect\glb_liscf_tsta0331_mainTESTS_R1_ALL_left_0103.exr --attrib "oiio:subimagename" "transmission_indirect" 
--siappendall -o \OIIO\debug_ligting\test_nuke.exr

The resulting EXR file can open whit RV Shotgun module but not when trying to open whith The Nuke Viewer

**Comment by lgritz** [comment] 2020-04-28 16:58
When you say "can open with RV Shotgun"... do you mean it opens, you can see all the different subimages, no errors?

When you say "not when trying to open with the Nuke viewer"... exactly what happens? Do you get an error message? Does Nuke crash? Can you see only some of the images?

What about if you use OIIO to re-split the big image:

    oiiotool test_nuke.exr  -sisplit -o:all=1 "sub%04d.tif"

Do you get all the separate subimages back, all readable and correct?

If you can use oiio to assemble the subimages into one file, and then correctly resplit, and if RV views the multi-part file okay, so it's only Nuke having the problem... I'm going to go out on a limb and say that maybe the problem is with Nuke and you should be asking them for help?

**Comment by lgritz** [comment] 2020-07-12 22:33
No follow-up for over two months, but I suspect that if the file opens properly with RV but not Nuke, maybe it's a problem with Nuke? Closing. Feel free to re-open if there is more information about what's happening.

**Closed by lgritz** 2020-07-12 22:33 UTC
