### ISSUE TITLE
Very Slowly Opening TIFF images issue 

### ISSUE THREAD

**Issue by MyunghoonSukTL** [OpenImageIO/oiio#1919] opened 2018-04-16 22:21 UTC
### Problem

**Expected & Actual behavior:**  
I have my code with oiio 1.7 for opening image files. I can open most tiff files fast without any issues, but sometimes a few tiff files saved by Adobe Photoshop take much longer time to open them. (for example, 40 or more seconds.) 
When I look into the tiffinput.cpp, some of tags set up by find_tag & get_xxx_attribute in such tiff files make longer processing time later. If I disable this block "Use the table for all the obvious things that can be mindlessly shoved into the image spec.", the tiff file is opened very fast, but image is not correct (black & white, wrong width and height, ...) because of no tiff information.
So I just suspect some of tags information in this kind of tiff. But I could not find exactly what tags are.  

Can anyone please help me to figure out what is causing this issue?

### Versions

* OIIO branch/version: 1.7.10
* OS: Mac
* C++ compiler:

**Comment by lgritz** [comment] 2018-04-16 22:32
Can you allow me to download one of the files that have this problem?

**Comment by MyunghoonSukTL** [comment] 2018-04-16 22:34
Sure. It's a big size. 108MB. Thanks!
https://www.dropbox.com/s/60kv8i1vucrjvec/slow_opening.tif?dl=0

**Comment by lgritz** [comment] 2018-04-16 22:35
Thanks, I'll look into this and get back to you here

**Comment by MyunghoonSukTL** [comment] 2018-04-16 22:37
I really appreciate it!

**Comment by lgritz** [comment] 2018-04-19 23:09
There are some interesting/unusual things about this file: It's large (you knew that -- 3556 x 4708), and the "rows per strip" is 4708 (the entire image is one single huge strip -- whereas something like 16 or 32 scanlines per strip is more typical), and it uses planarconfig "separate", and it's uncompressed.

I instrumented the code really carefully to time everything, and the bottom line is that all the time is spent inside calls to TIFFReadScanline, 50x longer than the same calls for the equivalent file I create with `tiffcp -r 32 slow_opening.tif slow_rps32.tif` (that is, an equivalent file with scanlines in 32-line strips). I tried rps=1000 and rps=100, and found that the speed seems to be proportional somehow to rps.

I tried to find out how fast it was if we used "contig" planar configuration, but still the huge rowsperstrip, and something curious happened: `tiffcp -p contig slow_opening.tif slow_contig.tif` for some reason writes a file with 1 row per strip! I tried forcing the original rps with `tiffcp -p contig -r 4708 slow_opening.tif slow_contig.tif`, and also got 1 rps. If I set rps=4707, it worked (for some reason, tiffcp is forcing at least 2 strips?), and it was fast -- 100x faster for each call to TIFFReadScanline. So large rps doesn't seem to hurt, as long as you are using contig planarconfig.

I'm not sure what's going on, and I'm not really inclined to try to debug this odd case in the internals of libtiff. But somehow the combination of scanline + very large strips + separate planarconfig == some big slowdown internal to libtiff. (Like you, I was seeing times of 30 seconds or more to read the whole file with OIIO, versus around 0.5s for the "fixed" file with normal rps.)

Note that in OIIO's TIFF output, we default to rps=32, and while we will honor other requests as communicated via the metadata "tiff:rowsperstrip", there is this curious code and comment (tiffoutput.cpp, circa line 566 in the current master):

    if (m_planarconfig == PLANARCONFIG_SEPARATE) {
        if (! m_spec.tile_width) {
            // I can only seem to make separate planarconfig work when
            // rowsperstrip is 1.
            m_rowsperstrip = 1;
            TIFFSetField (m_tif, TIFFTAG_ROWSPERSTRIP, 1);
        }
    }

I don't remember the history behind this, but I suspect that at some point in the past, I noticed weirdness with the interaction between separate planarconfig and certain values of rowsperstrip.

So, anyway, my recommendation is that you should see if you can get PhotoShop to output this file (a) with a smaller rows per strip (maybe even 1), and/or (b) output with planarconfig "contig" rather than "separate". I would also recommend writing the files with compression -- this was completely uncompressed -- but that wasn't the cause of the slowdown.

Now, as a mostly-separate issue, there's also something strange about the header that is making it quite expensive to open and read! This is a more minor effect -- reading the individual scanlines was taking TENS of seconds, reading the header metadata was taking less than ONE second, but it was still curiously expensive.

Let's look more carefully at using `tiffcp` (no OIIO involved here), and we note something curious in the console output:

    $ tiffcp slow_opening.tif slow2.tif
    TIFFReadDirectory: Warning, Unknown field with tag 37724 (0x935c) encountered.

That's funny, isn't it? And what's more, the resulting file slow2.tif is HALF the size of the original (50MB vs 108MB!), and reads the header in 0.1ms, versus 60ms for the original. 

Some playing with `tiffdump` also reveals that there is 58MB of data in the undocumented 37724 tag, apparently something that PhotoShop is adding. In addition to being wasteful in disk space, it is making the TIFFOpen and TIFFSetDirectory calls hundreds of times slower.

**Comment by MyunghoonSukTL** [comment] 2018-04-20 14:43
Hello Larry Gritz, 
I really appreciate your effort. I was just suspicious of something different in the tiff file, but I had no idea. It seems you found out a reason. Thank you so much! Let me test it again based on your result. I am thinking how to handle this kind of input tiff files when my program opens them. Of course, it would be great if oiio can handle this issue. I will be back with something else.

**Comment by MyunghoonSukTL** [comment] 2018-04-20 21:12
Hi Larry, 

  I was trying to find different options like smaller strips or contig/separate in Photoshop, but I could not find it. While the photoshop in a mac always can reproduce this kid of bad tiff with its default option, another mac cannot get this issue with default option in the same version of photoshop. It's weird!!
  I think using tiffcp as a workaround is not good option for my case. So I will try to modify TIFF reading to use strip-oriented I/O so that my program can handle this file silently.

**Comment by MyunghoonSukTL** [comment] 2018-04-20 21:41
I just found another open issue in the forum --
https://github.com/OpenImageIO/oiio/issues/1754
I think this is the same issue. 
He mentioned like this:
"I'm having very slow read performances when reading a RGB planar 4K TIF image. When saving the image as interleaved, it's way faster."

So I went back photoshop save option (pixel order), and I changed from "Per Channel" (my previous selection) to "Interleaved". Then the saved tiff got opened quickly. Now I can see the PlanarConfiguration is set from 2 to 1. (I think that 1 is contig and 2 is separate.)
<img width="579" alt="ps_tiff_options" src="https://user-images.githubusercontent.com/23464809/39074821-8f225738-44b8-11e8-991d-941021a1d0bb.png">

So for now I can use this workaround, but I would be happy if I get some improvement from oiio for this case.

Thanks Larry again for your efforts!

**Comment by lgritz** [comment] 2018-04-20 22:17
OK, let me take a stab at fixing the "separate" case with big strips. I think I know what to do. Glad you have a workaround so it's not an emergency, though.

In that TIFF dialog you posted... why not also try selecting image compression? I would suggest ZIP. There's no point that I can see to deliberately having no compression, when you could have lossless compression via either lzw or zip.

Aside: to give you an idea of how incredibly old this dialog is, and probably the underlying software as well... it describes the byte order as "IBM PC" (little endian, on Intel x86 chips) or "Macintosh" (big endian, on PowerPC CPUs). Except that Macs switched from PPC to x86 in 2006, so they have had the Intel byte order for over 10 years!

**Comment by lgritz** [comment] 2018-04-23 17:50
Proposed fix: #1925 

This speeds up loading of your test file from 35 seconds to under 2 seconds.

**Comment by MyunghoonSukTL** [comment] 2018-04-23 17:57
Yes! Thank you, Larry for great help as well as advice! For now, I am using the workaround. I am looking forward to fixing the "separate" case with big strips!! I really appreciate it!!

**Comment by lgritz** [comment] 2018-06-14 05:38
I think this has been resolved. Closing.

**Closed by lgritz** 2018-06-14 05:38 UTC
