### ISSUE TITLE
[BUG] unit_timer test unreliable

### ISSUE THREAD

**Issue by StefanBruens** [OpenImageIO/oiio#2628] opened 2020-07-05 15:36 UTC
The `all` timer is often more advanced in time then anticipated:

> [ 1082s] Timer begin/end cost is 8.01891e+06 /sec
> [ 1082s] Out of 10000000 queries, 9774796 had no time
> [ 1082s] Longest was 0.044141 s.
> [ 1082s] /home/abuild/rpmbuild/BUILD/oiio-Release-2.1.15.0/src/libutil/timer_test.cpp:117:
> [ 1082s] FAILED: all() == 0.3
> [ 1082s] 	values were '0.32099' and '0.3', diff was 0.02101
> [ 1082s] Checkpoint: All 0.321012 selective 0.104029
> [ 1082s] /home/abuild/rpmbuild/BUILD/oiio-Release-2.1.15.0/src/libutil/timer_test.cpp:125:
> [ 1082s] FAILED: all() == 0.4
> [ 1082s] 	values were '0.42114' and '0.4', diff was 0.021164
> [ 1082s] /home/abuild/rpmbuild/BUILD/oiio-Release-2.1.15.0/src/libutil/timer_test.cpp:129:
> [ 1082s] FAILED: all() == 0.5
> [ 1082s] 	values were '0.521279' and '0.5', diff was 0.021299
> [ 1082s] /home/abuild/rpmbuild/BUILD/oiio-Release-2.1.15.0/src/libutil/timer_test.cpp:136:
> [ 1082s] FAILED: all() == 0.5
> [ 1082s] 	values were '0.521304' and '0.5', diff was 0.021306
> [ 1082s] /home/abuild/rpmbuild/BUILD/oiio-Release-2.1.15.0/src/libutil/timer_test.cpp:140:
> [ 1082s] FAILED: all() == 0.6
> [ 1082s] 	values were '0.621423' and '0.6', diff was 0.021444
 
There are several reasons for this problem:
1. `Timer` uses `gettimeofday` on Linux, if the process is scheduled away, the timer still advances
2. The code does not account for its own runtime
3. The code does not account for usleep running *at least* the specified time [1]

[1] man 3 usleep:
> The usleep() function suspends execution of the calling thread for (at least) usec microseconds.  The sleep may be lengthened slightly by any system activity or by the time spent processing the call or by the granularity of system timers.

**Platform information:**
 - OIIO branch/version: 2.1.17
 - OS: Linux
 - C++ compiler: gcc10
 - Any non-default build flags when you build OIIO:

**Comment by lgritz** [comment] 2020-07-05 19:32
The Timer class is meant to measure elapsed time, not process time, so the fact that the timer advances if the process is scheduled away is a feature, not a bug.

This unit test is just trying to verify that Timer is working, and I couldn't think of much else to do in an automated way except for starting a timer, sleeping for an interval of t, and then verifying that the timer shows that approximately t has elapsed. 

Because I knew all along that sleep was inexact, the assertions in this test have quite a bit of timing slop built in, enough that it almost always passes (but would fail if we somehow totally broke the Timer class). Still, every once in a while, an overloaded machine will fall outside the accepted range and fail the test. If I see a test failure and it's only this test, and I look and see results like the above, I just ignore it. If it happens a lot on a particular platform, I will increase the allowable deviation (as I had to do a couple MacOS versions ago, when the scheduler changed to improve battery life on laptops in a way that made the usleep time a much looser guideline).

If you have a better suggestion for how to structure an automated test of the Timer class, I'm all ears.

If it is habitually and consistently failing for you, we can always increase the tolerance of the timing check.

**Comment by StefanBruens** [comment] 2020-07-05 20:12
1. Use `lap()` to reduce error accumulation
2. Use `RUN_SERIAL` label for [CMake ctest](https://cmake.org/cmake/help/v3.0/prop_test/RUN_SERIAL.html)
3. Consider instantiation time, already estimated:
> Longest was 0.044141 s.

The slop could be assymetric, elapsed time should *never* be smaller, but could be larger.

**Comment by lgritz** [comment] 2023-09-27 06:37
I believe this was fixed by #3953. Closing.

**Closed by lgritz** 2023-09-27 06:37 UTC
