### ISSUE TITLE
[BUG] iconvert not working -- image rotation

### ISSUE THREAD

**Issue by Dariusz1989** [OpenImageIO/oiio#3139] opened 2021-10-19 17:11 UTC
**Describe the bug**
I've installed OpenImageIO & openColorIO as I want to bake-aces to my exr files. But when I try to run for example >

openimageio\iconvert.exe  --inplace --rotcw "G:\private_CGI\2018-05-15_Vray4\images\tmp\camTest\Aces_test_01_masterLayer_01 - Copy.exr"

I get the exact same image out. No rotation. 

**To Reproduce**
.\vcpkg install opencolorio[tools]:x64-windows --recurse
.\vcpkg install openimageio[opencolorio,tools]:x64-windows --recurse

**Expected behavior**
Image to be rotated in place...

**Evidence**
No errror/etc

**Platform information:**
Windows 10x64
vcpkg manager

Can any1 suggest as to what I'm doing wrong here?

**Comment by lgritz** [comment] 2021-11-08 20:16
Did this adequately answer the question? Closing because I don't think there is a bug here, this is the expected behavior.

**Closed by lgritz** 2021-11-08 20:16 UTC
