### ISSUE TITLE
Memory leak in ustring?

### ISSUE THREAD

**Issue by tomansill** [OpenImageIO/oiio#1712] opened 2017-06-29 23:01 UTC
### Problem

I am using OpenImageIO for my project and I tried to run my project through valgrind memory leak checker and valgrind reports a multiple leaks. I have checked and checked over my code to make sure all of the memory are properly freed using ImageInput::destroy(), yet it still leaks. 

As a sanity check, I tried to use OpenImageIO's utility program like idiff and it reports a leak.

My hypothesis is that the leak may have occurred somewhere in OpenImageIO::ustring code, possibly around the "make_unique" function. I still don't have the solution yet as I am still looking through the code for solution. 

**Expected behavior:**  No leaks

**Actual behavior:**  It reports a leak.

Full leak log for idiff program: https://gist.github.com/tomansill/b49bac6f7299b4ed1444d4dd41f3b305

### Steps to Reproduce

Reproduce the issue using idiff program that is provided by the library: Get two random images. Make sure valgrind is installed.

0. Install Valgrind
1. `valgrind --leak-check=full idiff img1.jpg img2.jpg`
2. Observe the leak report

### Versions

* OIIO branch/version: 1.7.13
* OS: Arch Linux
* C++ compiler:  GCC 8.0 (I downloaded precompiled binary from Arch Linux's repository)

**Comment by lgritz** [comment] 2017-06-30 00:50
It's not a "leak", exactly. By design, the internal data structure that houses the ustring entries never frees those strings because we never want dangling pointers to them. The strings are meant to be persistent, and we must not invalidate them until all other data structures that reference them are no longer needed. Which is the very last moment of program operation, at which point it doesn't matter that we haven't freed it because in the next instant, the process will terminate and all heap memory will be reclaimed by the OS.

I guess it's technically possible carefully tear down the data structure teardown, but I'm not sure if it's worth the trouble and it would just complicate the code. There's nothing wrong with a process terminating while data structures are unfreed. In fact, it can be inefficient to laboriously tear down data structures when it's not needed to do so; when the program is done, it should exit as soon as possible.

The only problem is that valgrind's leak detection reports it -- it's a "false positive". I think the solution, if any is needed, is simply to have a way to tell Valgrind not to worry about any apparent leaks from allocations in make_unique. I'm sure there's a way to do this when invoking Valgrind (though I'm not sure how, off the top of my head). If there's also something we can do in the code itself, to mark that area as not something Valgrind should worry about, I'm happy to commit a proposed fix that does that.

**Comment by lgritz** [comment] 2017-07-10 22:56
Closing, unless somebody has a strong case for doing a careful tear-down of the ustring table.

**Closed by lgritz** 2017-07-10 22:56 UTC

**Comment by fpsunflower** [comment] 2017-07-10 23:03
Its not clear that a careful tear-down is possible since one might use `ustring` inside of other destructors.

Its the good old "static order initialization fiasco" feature of C++ [1]. Typically static order of _construction_ is possible (this is guaranteed by our implementation) but static order of _destruction_ is not. Since the destructors only have to free memory in this case, there is not much point using the (rather heavyweight) solutions here.

[1] https://isocpp.org/wiki/faq/ctors
