### ISSUE TITLE
Handles held when fails to load an image

### ISSUE THREAD

**Issue by monsieurgustav** [OpenImageIO/oiio#1034] opened 2015-01-21 16:52 UTC
Hi all,

When "ImageInput::create("test.tx")" is called, _test.tx being an empty file_, OIIO holds a file handle that cannot be released.
After a lot of calls, the opened handles per process limit is reached.

Observed on Windows 7, VS2012, x64, using procexp.exe.

Cheers,
Guillaume

**Comment by lgritz** [comment] 2018-12-23 07:30
Sorry this fell through the cracks.

I'm unable to reproduce this problem (at least, not on OSX). I'm going to assume that it was fixed long ago, so I'm going to close this issue.

If this can be reproduced on a current version of the software, please re-open.

**Closed by lgritz** 2018-12-23 07:30 UTC
