### ISSUE TITLE
OpenImageIO fails to open tiff file on CentOS 7.x.

### ISSUE THREAD

**Issue by fxwano** [OpenImageIO/oiio#964] opened 2014-09-24 01:26 UTC
I have been using OpenImageIO on CentOS 6.x with GCC 4.4.7.
Now, I'm testing CentOS 7.x with GCC 4.8.2.
OpenImageIO (both 1.4 and 1.5 ver.) works well in standalone c++ program.
But, I met Fatal Error while using it inside Maya.
I tested Maya 2013, 2014, and 2015, but they all closed with a message like this:

maya encountered a fatal error.
Signal: 11 (Unknown Signal)
Fatal Error Attempting to save in /usr/tmp/.....ma

I have no problem with other image formats such as *.jpg, *.tga, etc.
Only tiff (both 8-bit and 16-bit) shows the above error.

const char\* input = "test.tiff";
ImageInput\* in = ImageInput::create( input );
ImageSpec spec;
in->open( input, spec ); => THIS LINE OCCURS THE ERROR! 

I also tested LibTiff instead of OpenImageIO.
LibTiff has no problem to read and write *.tiff image format.

I installed Boost ver. 1.55.
I tried to install OpenImageIO with several different options, but always failed.

Could you give me a solution?

**Comment by lgritz** [comment] 2015-05-22 06:18
Is this still a problem with today's master?

**Comment by fxwano** [comment] 2015-05-22 06:25
I think that problem still exists today. I passed away that problem by
implementing my own .tiff file loading function.

Thank you.
 2015. 5. 22. 오후 3:18에 "Larry Gritz" <notifications@github.com>님이 작성:

**Comment by lgritz** [comment] 2015-05-22 06:29
Without a concrete example I can reproduce, closing.

**Comment by lumonix** [comment] 2017-03-23 18:51
Just a heads up, experienced similar issue when we switch to vfx2016a at Pixar while trying to load a .tif.
Tried re-saving the tif with various compression schemes, but still crashed.
In your case we just switched these .tif files to PNG due to time constraints (they are only icons).

My apologies for note providing a more complete repro, but wanted to leave a note in case somebody else runs into it with more time to provide a simple repro.

Code (from internal tool):
        ImageInput *in = 0;
        in = ImageInput::create(path);
        ImageSpec spec;
        if (in && in->open(path, spec))


Callstack:

#0  waitpid ()+0x69 from /lib64/libpthread.so.0
#1  ArchCrashHandlerSystemv(char const*, char* const*, int, void (*)(void*), void*) ()+0xda from /usr/anim/toolsrels/pxr-dev-daily.00398/lib/libarch.so
#2  ArchLogPostMortem(char const*, char const*) ()+0x644 from /usr/anim/toolsrels/pxr-dev-daily.00398/lib/libarch.so
#3  _fatalSignalHandler(int, siginfo_t*, void*) ()+0x30 from /usr/anim/toolsrels/pxr-dev-daily.00398/lib/libtf.so
#4  <signal handler called>
#5  TIFFFindField () [0x7fab82afccbe] from /lib64/libtiff.so.5
#6  OpenImageIO::v1_5::TIFFInput::find_tag(int, TIFFDataType, char const*) ()+0x24 from fedora-11-x86_64/vfx2016a/packages/openimageio-1.5.11/lib/libOpenImageIO.so.1.5
#7  OpenImageIO::v1_5::TIFFInput::readspec(bool) ()+0x314 from /fedora-11-x86_64/vfx2016a/packages/openimageio-1.5.11/lib/libOpenImageIO.so.1.5
#8  OpenImageIO::v1_5::TIFFInput::seek_subimage(int, int, OpenImageIO::v1_5::ImageSpec&) ()+0x87 from /fedora-11-x86_64/vfx2016a/packages/openimageio-1.5.11/lib/libOpenImageIO.so.1.5
#9  0x00000000005a8e42 in imageUtils::LoadImage(std::string const&, ItImage&, int) ()

**Comment by lgritz** [comment] 2017-03-23 18:59
Do you know...
1. Which version of libtiff?
2. If it's still a problem in a more modern OIIO (1.7 or master)?
3. If it did this for ALL tiff files, or just particular ones?
4. If the latter, is there any chance you can send me one that fails?

**Comment by lumonix** [comment] 2017-03-23 22:04
(sent tif via email)

libtiff-4.0.3-14.el7.x86_64
libtiff-4.0.3-14.el7.i686

**Comment by lgritz** [comment] 2017-03-24 23:06
Off-list emails with @lumonix :. this was tracked down to a TIFF library mismatch issue on his end -- there were two libtiff .so's of different versions lying around. So I'm going to close this ticket.

Interestingly, here at SPI we had a similar problem when we upgraded to rhel/centos 7 -- I think we had two .so's but the headers for only one of them, so if you build OIIO using one set of headers that didn't match the library that was loaded dynamically, it was trouble.

So be safe with your libraries, people!

**Closed by lgritz** 2017-03-24 23:06 UTC
