### ISSUE TITLE
[BUG] Unexpected behavior of ImageBuf::reset()

### ISSUE THREAD

**Issue by ttddee** [OpenImageIO/oiio#2458] opened 2020-01-09 08:49 UTC
**Describe the bug**

In the documentation for ImageBuf::reset() it says:

> Re-initialize as a writeable ImageBuf with the given specification (including resolution, data type, metadata, etc.). The optional zero parameter controls whether the pixel values are filled with black/empty, or are left uninitialized after being allocated (if set to InitializePixels::No).

Maybe it is just the wording in the documentation but whether or not you initialize the pixels does not affect if the ImageBuf itself gets initialized. 

If you want the ImageBuf itself to be initialized you need to pass it a ImageSpec that has the format set, although you might be resetting a Buf that knows its format already.

Passing a Spec without the format set will not initialize the ImageBuf, no matter what the other options are.

**Steps to reproduce the behavior:**

    std::shared_ptr<ImageBuf> img (new ImageBuf("/tmp/test.jpg"));

    std::cout << "Initialized: " << img->initialized() << std::endl;

    ImageSpec sp;
    sp.width = 400;
    sp.height = 400;
    sp.nchannels = 3;
    img->reset(sp, InitializePixels::Yes);

    std::cout << "Initialized: " << img->initialized() << std::endl;

    ImageSpec sp2;
    sp2.set_format(TypeDesc::FLOAT);
    img->reset(sp2, InitializePixels::No);

    std::cout << "Initialized: " << img->initialized() << std::endl;

Output:

    Initialized: 1
    Initialized: 0
    Initialized: 1

**Expected behavior**

    Initialized: 1
    Initialized: 1
    Initialized: 1

**Comment by lgritz** [comment] 2020-01-10 01:22
I think that maybe we can chalk this one up to unclear documentation, and an unfortunate use of the word "initialize" to mean two different things.

An ImageBuf currently can be in one of four states: 
* LOCALBUFFER -- a read/write ImageBuf that internally owns allocated memory to store its pixels.
* APPBUFFER -- a read/write ImageBuf that refers (in a non-owning way) to pixel memory that lives somewhere else. This is how we make a light-weight ImageBuf that "wraps" some other application-owned memory. The only difference between LOCALBUFFER and APPBUFFER is that the latter does not free the internal pointer when it is destructed or reset.
* IMAGECACHE -- a read-only ImageBuf giving a virtualized view of an image that lives on disk (using ImageCache underneath), so that it (and other IB's using the same cache as a backing) are only loading parts of image as needed and keeping the total memory low even though it appears that you may have thousands of images totaling many TB.
* UNINITIALIZED -- this is essentially a newly constructed "empty" IB that doesn't have any pixels, nor does it refer to any disk file.

So in this case, "initialized" and the `img->initialized()` call are referring to whether this IB has pixels (virtualized or not, read or not), or is it just an empty / newly constructed container.

I should also add that the various `reset()` methods are meant to completely restore the state of an IB to how it would be when newly constructed. In particular:

    // This...
    ImageBuf (...ctr args...) bufA;

    // is exactly identical to:
    ImageBuf bufB;   // default constructor
    bufB.reset(...ctr args...);

So for the rest of this discussion, I will refer to constructors, but the same things I believe will always apply to using the `reset()` method (even if the ImageBuf you are resetting used to contain things).

OK, so...

It looks like the constructor `ImageBuf(const ImageSpec& spec, InitializePixels zero)` -- which is ordinarily used to create a writeable IB with local storage -- seems to have the behavior that if the ImageSpec you pass has not set its `format` field (and thus defaults to `TypeDesc::UNKNOWN`), the buffer will remain more or less in the `UNINITIALIZED` state.  

Which makes sense, since it can't allocate space for pixels if you haven't told it what data type to use.

That's why your second example yields an IB that says `initialized()` is false. You are asking for an ImageBuf with local/owned pixel storage, but you haven't given it all the information it needs to properly allocate that storage.

Now then, what about the second parameter, `InitializePixels zero`?

What this parameter is controlling is whether, as the IB is initialized and allocating memory for the pixels, should it fill that memory with zero values, or should it leave the memory "uninitialized"? (If you want a black image, you say Yes. If you are about to write something totally different into that image and it would be a waste of time to needlessly traverse that memory to zero it out, then you say No.)

So, ick, I'm really sorry. One thing is referring to whether the **ImageBuf** is initialized (versus looking like a default constructed empty IB), and the other thing is about whether the allocated pixel memory has been initialized with zero values or if the pixel memory contents are uninitialized (essentially might contain random values).

I think the behavior here is correct, though in retrospect I could have named the parameter something more clear.

**Comment by lgritz** [comment] 2020-01-10 01:28
A much briefer answer:

Of course the ImageBuf is "uninitialized" if you construct it from an incomplete ImageSpec that doesn't specify a pixel type.

The fact that it "knew its pixel type already" is irrelevant, since reset() is by design supposed to put the buffer in a state that is identical to a newly constructed IB.

I will review the documentation to see if there is a way I can clarify this.

**Comment by ttddee** [comment] 2020-01-10 07:57
Thank you for the detailed explanation! 

I was somehow under the impression that the ImageBuf would "remember" its format, but since we are giving it a new ImageSpec, why would it.

This is not an issue then but rather just a lack of understanding on my side.

**Comment by lgritz** [comment] 2020-01-10 08:00
I don't think there is any behavior to change, but this has inspired me to do a big overhaul of the documented description of the IB constructors. Stay tuned, I'll post tomorrow and would appreciate any feedback on whether you think it clarifies the behavior.

**Comment by lgritz** [comment] 2020-01-12 06:24
I made some improvements in #2460

**Comment by ttddee** [comment] 2020-01-12 08:26
Looks good!

I like that this:

    ImageSpec sp;
    sp.set_format(TypeDesc::FLOAT);
    img->reset(sp);

no longer initializes. Before it would give me an ImageBuf with WxHxC = 1x1x1 which is basically useless.

**Comment by lgritz** [comment] 2020-01-12 16:51
Fixed by #2460.

**Closed by lgritz** 2020-01-12 16:51 UTC
