### ISSUE TITLE
identifying openEXR layers and reading their pixels?

### ISSUE THREAD

**Issue by fredlllll** [OpenImageIO/oiio#2269] opened 2019-06-25 10:19 UTC
hi there,

for my project i need to read multilayer EXRs. but i dont get how i get the layers names and how i read the layers each. anyone knows this?

**Comment by lgritz** [comment] 2019-06-25 15:07
Hi. "How do I?" sort of questions are really better asked on the oiio-dev mail list. We use GitHub "issues" to report and track bugs or feature requests.

But I'll try to answer your question here nonetheless. 

There are two related concepts with OpenEXR -- (1) multi-part exr files, and (2) what people call "multi-layer" files.

A multi-part file looks to OIIO like an image file with multiple subimages. The OIIO docs are pretty comprehensive, I would direct you there for reading subimages.

A "multi-layer" file is just a single subimages with LOTS of color channels, where the color channels have a naming scheme "layer.channel". So maybe you'll have six channels, called "diffuse.R", "diffuse.G", "diffuse.B", "specular.R", "specular.G", "specular.B". That means there are two layers, "diffuse" and "specular". I think you just need to look at the channel names, sort them and look for channels with "." in their name, and then the layers are the unique names found before the dots. That's not a separate concept with OIIO, you just have to do that part in your code.

I'm closing, since this is not a bug or a feature request. Please direct follow-up questions to the oiio-dev mail list.

**Closed by lgritz** 2019-06-25 15:07 UTC
