### ISSUE TITLE
Most PNG images can no longer be read

### ISSUE THREAD

**Issue by gregcotten** [OpenImageIO/oiio#2218] opened 2019-04-24 01:41 UTC
### Problem

Opening a PNG used to work, now it doesn't.

### Steps to Reproduce

1. Run ```iinfo``` on [this png](https://www.dropbox.com/s/fhsywqydg4dstm5/Rectangle.png?dl=0) or [this png](https://www.dropbox.com/s/0zxe5gasvw173u4/4x4Checker.png?dl=0)
2. Get error: ```iinfo ERROR: Could not create PNG read structure```

### Versions

* OIIO branch/version: 2.0.7
* libpng version: 1.6.37
* OS: macOS 10.13 or 10.14
* C++ compiler: Apple LLVM version 10.0.0 (clang-1000.11.45.5)

**Comment by gregcotten** [comment] 2019-04-24 01:44
Strangely is not due to #2167 as I can get the PNG to read in 2.0.6

**Comment by lgritz** [comment] 2019-04-24 02:04
Awesome, I will take a look right away.

**Comment by gregcotten** [comment] 2019-04-24 02:17
Looks like the PNG test images on the olio-images repo don't load either.

**Comment by lgritz** [comment] 2019-04-24 06:04
I can't reproduce with current master, current RB-2.0 head, or at the Release-2.0.6 tag, with my MacOS 10.14.4, LLVM 10.0.1, libpng 1.6.37 (from homebrew), either release or debug build. :-(

Can you post me the full (VERBOSE=1) log that shows the cmake setup and any additional options you used? For example,

    make nuke
    make VERBOSE=1 > build.log

Also, does it fail for you on the current master as well?

**Comment by lgritz** [comment] 2019-04-24 06:09
I'm sorry to ask you to do this, but If it fails for you at the 2.0.6 tag, can you try 2.0.5, etc., and narrow it down to a release? Or, if you really are a saint, bisect and narrow it down to a commit?

When you say "iinfo" has that error -- with any particular flags? You are just running `iinfo Rectangle.png` to get that message?

**Comment by gregcotten** [comment] 2019-04-24 15:54
Oh yea ```iinfo Rectangle.png```. This is with OIIO 2.0.7. 2.0.6 has no such issue. I could bisect, but I'll try master first and see if it's fixed.

**Comment by lgritz** [comment] 2019-04-24 17:07
The weird thing is that between 2.0.6 and 2.0.7, there were no direct changes to the png code.

The only thing that looks suspicious is commit 5579d9, which is PR 2185 -- that changed some of the logic of deciding which format reader to invoke.

Could you test at the point of commit 5579d9 versus the commit immediately prior to it?

**Comment by gregcotten** [comment] 2019-04-25 20:11
Well, it may be High Sierra related. I've built on my Mojave 10.14.4 install (with latest everything from homebrew) and it works just fine. I'll boot up my High Sierra machine in a bit and see what's up.

**Comment by lgritz** [comment] 2019-05-03 19:05
Proposed fix:  https://github.com/OpenImageIO/oiio/pull/2231

**Comment by gregcotten** [comment] 2019-05-03 19:08
Interesting - this problem was specifically when built on macOS 10.13 so
I’m not sure the MS fix would help. When compiled on Mojave with latest
Cmake and other dependencies, PNGs load in just fine.

**Comment by lgritz** [comment] 2019-05-03 19:12
Oh, sorry, I saw "PNG" and thought this was one of the same problems.
Never mind, you're right, that can't be the same issue.

**Comment by lgritz** [comment] 2019-05-03 19:12
But in any case, since you are ok for now, I will close the issue.

**Closed by lgritz** 2019-05-03 19:12 UTC
